;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 07/05/2026 08:34:12
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2804			GOTO	_main
$0688	$	_delay_1us:
;delays.pbas,9 :: 		sub procedure Delay_1us()
;delays.pbas,10 :: 		Delay_us(1)
$0688	$0000			NOP
$0689	$	delays_L_1:
$0689	$0008			RETURN
$0651	$	_delay_5500us:
;delays.pbas,33 :: 		sub procedure Delay_5500us()
;delays.pbas,34 :: 		Delay_us(5500)
$0651	$3008			MOVLW	8
$0652	$1303			BCF	STATUS, RP1
$0653	$1283			BCF	STATUS, RP0
$0654	$00FB			MOVWF	STACK_11
$0655	$30FF			MOVLW	255
$0656	$00FA			MOVWF	STACK_10
$0657	$0BFB			DECFSZ	STACK_11, F
$0658	$2E5A			GOTO	$+2
$0659	$2E5D			GOTO	$+4
$065A	$0BFA			DECFSZ	STACK_10, F
$065B	$2E5A			GOTO	$-1
$065C	$2E57			GOTO	$-5
$065D	$301E			MOVLW	30
$065E	$00FA			MOVWF	STACK_10
$065F	$0BFA			DECFSZ	STACK_10, F
$0660	$2E5F			GOTO	$-1
$0661	$	delays_L_7:
$0661	$0008			RETURN
$0679	$	_delay_50us:
;delays.pbas,21 :: 		sub procedure Delay_50us()
;delays.pbas,22 :: 		Delay_us(50)
$0679	$3010			MOVLW	16
$067A	$1303			BCF	STATUS, RP1
$067B	$1283			BCF	STATUS, RP0
$067C	$00FA			MOVWF	STACK_10
$067D	$0BFA			DECFSZ	STACK_10, F
$067E	$2E7D			GOTO	$-1
$067F	$0000			NOP
$0680	$	delays_L_4:
$0680	$0008			RETURN
$03CE	$	_lcd_cmd:
;lcd.ppas,19 :: 		
;lcd.ppas,20 :: 		
$03CE	$1303			BCF	STATUS, RP1
$03CF	$1283			BCF	STATUS, RP0
$03D0	$0820			MOVF	lcd_ctrlport_address, 0
$03D1	$0084			MOVWF	FSR
;lcd.ppas,22 :: 		
$03D2	$0921			COMF	lcd____menable, W
$03D3	$00F0			MOVWF	STACK_0
$03D4	$0870			MOVF	STACK_0, 0
$03D5	$0580			ANDWF	INDF, 1
;lcd.ppas,23 :: 		
$03D6	$0922			COMF	lcd____mrs, W
$03D7	$00F0			MOVWF	STACK_0
$03D8	$0870			MOVF	STACK_0, 0
$03D9	$0580			ANDWF	INDF, 1
;lcd.ppas,25 :: 		
$03DA	$0823			MOVF	lcd_dataport_address, 0
$03DB	$0084			MOVWF	FSR
;lcd.ppas,26 :: 		
$03DC	$0825			MOVF	lcd____mdb6, 0
$03DD	$0424			IORWF	lcd____mdb7, 0
$03DE	$00F0			MOVWF	STACK_0
$03DF	$0826			MOVF	lcd____mdb5, 0
$03E0	$04F0			IORWF	STACK_0, 1
$03E1	$0827			MOVF	lcd____mdb4, 0
$03E2	$04F0			IORWF	STACK_0, 1
$03E3	$09F0			COMF	STACK_0, F
$03E4	$0870			MOVF	STACK_0, 0
$03E5	$0580			ANDWF	INDF, 1
;lcd.ppas,28 :: 		
$03E6	$3000			MOVLW	0
$03E7	$1BDB			BTFSC	FARG_Lcd_Cmd, 7
$03E8	$3001			MOVLW	1
$03E9	$00F1			MOVWF	STACK_1
$03EA	$0871			MOVF	STACK_1, 0
$03EB	$3A01			XORLW	1
$03EC	$1D03			BTFSS	STATUS, Z
$03ED	$2BF0			GOTO	lcd_L_2
$03EE	$	lcd_L_1:
;lcd.ppas,29 :: 		
$03EE	$0824			MOVF	lcd____mdb7, 0
$03EF	$0480			IORWF	INDF, 1
$03F0	$	lcd_L_2:
$03F0	$	lcd_L_3:
;lcd.ppas,30 :: 		
$03F0	$3000			MOVLW	0
$03F1	$1B5B			BTFSC	FARG_Lcd_Cmd, 6
$03F2	$3001			MOVLW	1
$03F3	$00F1			MOVWF	STACK_1
$03F4	$0871			MOVF	STACK_1, 0
$03F5	$3A01			XORLW	1
$03F6	$1D03			BTFSS	STATUS, Z
$03F7	$2BFA			GOTO	lcd_L_5
$03F8	$	lcd_L_4:
;lcd.ppas,31 :: 		
$03F8	$0825			MOVF	lcd____mdb6, 0
$03F9	$0480			IORWF	INDF, 1
$03FA	$	lcd_L_5:
$03FA	$	lcd_L_6:
;lcd.ppas,32 :: 		
$03FA	$3000			MOVLW	0
$03FB	$1ADB			BTFSC	FARG_Lcd_Cmd, 5
$03FC	$3001			MOVLW	1
$03FD	$00F1			MOVWF	STACK_1
$03FE	$0871			MOVF	STACK_1, 0
$03FF	$3A01			XORLW	1
$0400	$1D03			BTFSS	STATUS, Z
$0401	$2C04			GOTO	lcd_L_8
$0402	$	lcd_L_7:
;lcd.ppas,33 :: 		
$0402	$0826			MOVF	lcd____mdb5, 0
$0403	$0480			IORWF	INDF, 1
$0404	$	lcd_L_8:
$0404	$	lcd_L_9:
;lcd.ppas,34 :: 		
$0404	$3000			MOVLW	0
$0405	$1A5B			BTFSC	FARG_Lcd_Cmd, 4
$0406	$3001			MOVLW	1
$0407	$00F1			MOVWF	STACK_1
$0408	$0871			MOVF	STACK_1, 0
$0409	$3A01			XORLW	1
$040A	$1D03			BTFSS	STATUS, Z
$040B	$2C0E			GOTO	lcd_L_11
$040C	$	lcd_L_10:
;lcd.ppas,35 :: 		
$040C	$0827			MOVF	lcd____mdb4, 0
$040D	$0480			IORWF	INDF, 1
$040E	$	lcd_L_11:
$040E	$	lcd_L_12:
;lcd.ppas,37 :: 		
$040E	$0820			MOVF	lcd_ctrlport_address, 0
$040F	$0084			MOVWF	FSR
;lcd.ppas,38 :: 		
$0410	$0828			MOVF	lcd_lcdcmd_status, 0
$0411	$3A01			XORLW	1
$0412	$1D03			BTFSS	STATUS, Z
$0413	$2C19			GOTO	lcd_L_14
$0414	$	lcd_L_13:
;lcd.ppas,39 :: 		
$0414	$0922			COMF	lcd____mrs, W
$0415	$00F0			MOVWF	STACK_0
$0416	$0870			MOVF	STACK_0, 0
$0417	$0580			ANDWF	INDF, 1
$0418	$2C1B			GOTO	lcd_L_15
;lcd.ppas,40 :: 		
$0419	$	lcd_L_14:
;lcd.ppas,41 :: 		
$0419	$0822			MOVF	lcd____mrs, 0
$041A	$0480			IORWF	INDF, 1
$041B	$	lcd_L_15:
;lcd.ppas,43 :: 		
$041B	$0821			MOVF	lcd____menable, 0
$041C	$0480			IORWF	INDF, 1
;lcd.ppas,44 :: 		
$041D	$2688			CALL	_delay_1us
;lcd.ppas,45 :: 		
$041E	$0921			COMF	lcd____menable, W
$041F	$00F0			MOVWF	STACK_0
$0420	$0870			MOVF	STACK_0, 0
$0421	$0580			ANDWF	INDF, 1
;lcd.ppas,47 :: 		
$0422	$0922			COMF	lcd____mrs, W
$0423	$00F0			MOVWF	STACK_0
$0424	$0870			MOVF	STACK_0, 0
$0425	$0580			ANDWF	INDF, 1
;lcd.ppas,49 :: 		
$0426	$0823			MOVF	lcd_dataport_address, 0
$0427	$0084			MOVWF	FSR
;lcd.ppas,50 :: 		
$0428	$0825			MOVF	lcd____mdb6, 0
$0429	$0424			IORWF	lcd____mdb7, 0
$042A	$00F0			MOVWF	STACK_0
$042B	$0826			MOVF	lcd____mdb5, 0
$042C	$04F0			IORWF	STACK_0, 1
$042D	$0827			MOVF	lcd____mdb4, 0
$042E	$04F0			IORWF	STACK_0, 1
$042F	$09F0			COMF	STACK_0, F
$0430	$0870			MOVF	STACK_0, 0
$0431	$0580			ANDWF	INDF, 1
;lcd.ppas,52 :: 		
$0432	$3000			MOVLW	0
$0433	$19DB			BTFSC	FARG_Lcd_Cmd, 3
$0434	$3001			MOVLW	1
$0435	$00F1			MOVWF	STACK_1
$0436	$0871			MOVF	STACK_1, 0
$0437	$3A01			XORLW	1
$0438	$1D03			BTFSS	STATUS, Z
$0439	$2C3C			GOTO	lcd_L_17
$043A	$	lcd_L_16:
;lcd.ppas,53 :: 		
$043A	$0824			MOVF	lcd____mdb7, 0
$043B	$0480			IORWF	INDF, 1
$043C	$	lcd_L_17:
$043C	$	lcd_L_18:
;lcd.ppas,54 :: 		
$043C	$3000			MOVLW	0
$043D	$195B			BTFSC	FARG_Lcd_Cmd, 2
$043E	$3001			MOVLW	1
$043F	$00F1			MOVWF	STACK_1
$0440	$0871			MOVF	STACK_1, 0
$0441	$3A01			XORLW	1
$0442	$1D03			BTFSS	STATUS, Z
$0443	$2C46			GOTO	lcd_L_20
$0444	$	lcd_L_19:
;lcd.ppas,55 :: 		
$0444	$0825			MOVF	lcd____mdb6, 0
$0445	$0480			IORWF	INDF, 1
$0446	$	lcd_L_20:
$0446	$	lcd_L_21:
;lcd.ppas,56 :: 		
$0446	$3000			MOVLW	0
$0447	$18DB			BTFSC	FARG_Lcd_Cmd, 1
$0448	$3001			MOVLW	1
$0449	$00F1			MOVWF	STACK_1
$044A	$0871			MOVF	STACK_1, 0
$044B	$3A01			XORLW	1
$044C	$1D03			BTFSS	STATUS, Z
$044D	$2C50			GOTO	lcd_L_23
$044E	$	lcd_L_22:
;lcd.ppas,57 :: 		
$044E	$0826			MOVF	lcd____mdb5, 0
$044F	$0480			IORWF	INDF, 1
$0450	$	lcd_L_23:
$0450	$	lcd_L_24:
;lcd.ppas,58 :: 		
$0450	$3001			MOVLW	1
$0451	$055B			ANDWF	FARG_Lcd_Cmd, 0
$0452	$00F1			MOVWF	STACK_1
$0453	$0871			MOVF	STACK_1, 0
$0454	$3A01			XORLW	1
$0455	$1D03			BTFSS	STATUS, Z
$0456	$2C59			GOTO	lcd_L_26
$0457	$	lcd_L_25:
;lcd.ppas,59 :: 		
$0457	$0827			MOVF	lcd____mdb4, 0
$0458	$0480			IORWF	INDF, 1
$0459	$	lcd_L_26:
$0459	$	lcd_L_27:
;lcd.ppas,61 :: 		
$0459	$0820			MOVF	lcd_ctrlport_address, 0
$045A	$0084			MOVWF	FSR
;lcd.ppas,62 :: 		
$045B	$0828			MOVF	lcd_lcdcmd_status, 0
$045C	$3A01			XORLW	1
$045D	$1D03			BTFSS	STATUS, Z
$045E	$2C64			GOTO	lcd_L_29
$045F	$	lcd_L_28:
;lcd.ppas,63 :: 		
$045F	$0922			COMF	lcd____mrs, W
$0460	$00F0			MOVWF	STACK_0
$0461	$0870			MOVF	STACK_0, 0
$0462	$0580			ANDWF	INDF, 1
$0463	$2C66			GOTO	lcd_L_30
;lcd.ppas,64 :: 		
$0464	$	lcd_L_29:
;lcd.ppas,65 :: 		
$0464	$0822			MOVF	lcd____mrs, 0
$0465	$0480			IORWF	INDF, 1
$0466	$	lcd_L_30:
;lcd.ppas,67 :: 		
$0466	$0821			MOVF	lcd____menable, 0
$0467	$0480			IORWF	INDF, 1
;lcd.ppas,68 :: 		
$0468	$2688			CALL	_delay_1us
;lcd.ppas,69 :: 		
$0469	$0921			COMF	lcd____menable, W
$046A	$00F0			MOVWF	STACK_0
$046B	$0870			MOVF	STACK_0, 0
$046C	$0580			ANDWF	INDF, 1
;lcd.ppas,71 :: 		
$046D	$0828			MOVF	lcd_lcdcmd_status, 0
$046E	$3A01			XORLW	1
$046F	$1D03			BTFSS	STATUS, Z
$0470	$2C73			GOTO	lcd_L_32
$0471	$	lcd_L_31:
;lcd.ppas,72 :: 		
$0471	$2651			CALL	_delay_5500us
$0472	$2C74			GOTO	lcd_L_33
;lcd.ppas,73 :: 		
$0473	$	lcd_L_32:
;lcd.ppas,74 :: 		
$0473	$2679			CALL	_delay_50us
$0474	$	lcd_L_33:
$0474	$	lcd_L_0:
;lcd.ppas,75 :: 		
$0474	$0008			RETURN
$0181	$	_lcd_config:
;lcd.ppas,115 :: 		
;lcd.ppas,116 :: 		
$0181	$2651			CALL	_delay_5500us
;lcd.ppas,117 :: 		
$0182	$2651			CALL	_delay_5500us
;lcd.ppas,118 :: 		
$0183	$2651			CALL	_delay_5500us
;lcd.ppas,120 :: 		
$0184	$0853			MOVF	FARG_Lcd_Config+1, 0
$0185	$00F0			MOVWF	STACK_0
$0186	$3001			MOVLW	1
$0187	$00F4			MOVWF	STACK_4
$0188	$0870			MOVF	STACK_0, 0
$0189	$	L_Lcd_Config_0:
$0189	$1903			BTFSC	STATUS, Z
$018A	$298F			GOTO	L_Lcd_Config_1
$018B	$0DF4			RLF	STACK_4, 1
$018C	$1074			BCF	STACK_4, 0
$018D	$3FFF			ADDLW	255
$018E	$2989			GOTO	L_Lcd_Config_0
$018F	$	L_Lcd_Config_1:
$018F	$0874			MOVF	STACK_4, 0
$0190	$00A4			MOVWF	lcd____mdb7
;lcd.ppas,121 :: 		
$0191	$0854			MOVF	FARG_Lcd_Config+2, 0
$0192	$00F0			MOVWF	STACK_0
$0193	$3001			MOVLW	1
$0194	$00F3			MOVWF	STACK_3
$0195	$0870			MOVF	STACK_0, 0
$0196	$	L_Lcd_Config_2:
$0196	$1903			BTFSC	STATUS, Z
$0197	$299C			GOTO	L_Lcd_Config_3
$0198	$0DF3			RLF	STACK_3, 1
$0199	$1073			BCF	STACK_3, 0
$019A	$3FFF			ADDLW	255
$019B	$2996			GOTO	L_Lcd_Config_2
$019C	$	L_Lcd_Config_3:
$019C	$0873			MOVF	STACK_3, 0
$019D	$00A5			MOVWF	lcd____mdb6
;lcd.ppas,122 :: 		
$019E	$0855			MOVF	FARG_Lcd_Config+3, 0
$019F	$00F0			MOVWF	STACK_0
$01A0	$3001			MOVLW	1
$01A1	$00F2			MOVWF	STACK_2
$01A2	$0870			MOVF	STACK_0, 0
$01A3	$	L_Lcd_Config_4:
$01A3	$1903			BTFSC	STATUS, Z
$01A4	$29A9			GOTO	L_Lcd_Config_5
$01A5	$0DF2			RLF	STACK_2, 1
$01A6	$1072			BCF	STACK_2, 0
$01A7	$3FFF			ADDLW	255
$01A8	$29A3			GOTO	L_Lcd_Config_4
$01A9	$	L_Lcd_Config_5:
$01A9	$0872			MOVF	STACK_2, 0
$01AA	$00A6			MOVWF	lcd____mdb5
;lcd.ppas,123 :: 		
$01AB	$0856			MOVF	FARG_Lcd_Config+4, 0
$01AC	$00F0			MOVWF	STACK_0
$01AD	$3001			MOVLW	1
$01AE	$00F1			MOVWF	STACK_1
$01AF	$0870			MOVF	STACK_0, 0
$01B0	$	L_Lcd_Config_6:
$01B0	$1903			BTFSC	STATUS, Z
$01B1	$29B6			GOTO	L_Lcd_Config_7
$01B2	$0DF1			RLF	STACK_1, 1
$01B3	$1071			BCF	STACK_1, 0
$01B4	$3FFF			ADDLW	255
$01B5	$29B0			GOTO	L_Lcd_Config_6
$01B6	$	L_Lcd_Config_7:
$01B6	$0871			MOVF	STACK_1, 0
$01B7	$00A7			MOVWF	lcd____mdb4
;lcd.ppas,124 :: 		
$01B8	$0858			MOVF	FARG_Lcd_Config+6, 0
$01B9	$00F0			MOVWF	STACK_0
$01BA	$3001			MOVLW	1
$01BB	$00A2			MOVWF	lcd____mrs
$01BC	$0870			MOVF	STACK_0, 0
$01BD	$	L_Lcd_Config_8:
$01BD	$1903			BTFSC	STATUS, Z
$01BE	$29C3			GOTO	L_Lcd_Config_9
$01BF	$0DA2			RLF	lcd____mrs, 1
$01C0	$1022			BCF	lcd____mrs, 0
$01C1	$3FFF			ADDLW	255
$01C2	$29BD			GOTO	L_Lcd_Config_8
$01C3	$	L_Lcd_Config_9:
;lcd.ppas,125 :: 		
$01C3	$0859			MOVF	FARG_Lcd_Config+7, 0
$01C4	$00F0			MOVWF	STACK_0
$01C5	$3001			MOVLW	1
$01C6	$00A9			MOVWF	lcd____mrw
$01C7	$0870			MOVF	STACK_0, 0
$01C8	$	L_Lcd_Config_10:
$01C8	$1903			BTFSC	STATUS, Z
$01C9	$29CE			GOTO	L_Lcd_Config_11
$01CA	$0DA9			RLF	lcd____mrw, 1
$01CB	$1029			BCF	lcd____mrw, 0
$01CC	$3FFF			ADDLW	255
$01CD	$29C8			GOTO	L_Lcd_Config_10
$01CE	$	L_Lcd_Config_11:
;lcd.ppas,126 :: 		
$01CE	$085A			MOVF	FARG_Lcd_Config+8, 0
$01CF	$00F0			MOVWF	STACK_0
$01D0	$3001			MOVLW	1
$01D1	$00A1			MOVWF	lcd____menable
$01D2	$0870			MOVF	STACK_0, 0
$01D3	$	L_Lcd_Config_12:
$01D3	$1903			BTFSC	STATUS, Z
$01D4	$29D9			GOTO	L_Lcd_Config_13
$01D5	$0DA1			RLF	lcd____menable, 1
$01D6	$1021			BCF	lcd____menable, 0
$01D7	$3FFF			ADDLW	255
$01D8	$29D3			GOTO	L_Lcd_Config_12
$01D9	$	L_Lcd_Config_13:
;lcd.ppas,128 :: 		
$01D9	$0852			MOVF	FARG_Lcd_Config, 0
$01DA	$00A3			MOVWF	lcd_dataport_address
;lcd.ppas,129 :: 		
$01DB	$0857			MOVF	FARG_Lcd_Config+5, 0
$01DC	$00A0			MOVWF	lcd_ctrlport_address
;lcd.ppas,131 :: 		
$01DD	$0852			MOVF	FARG_Lcd_Config, 0
$01DE	$0084			MOVWF	FSR
;lcd.ppas,133 :: 		
$01DF	$0873			MOVF	STACK_3, 0
$01E0	$0474			IORWF	STACK_4, 0
$01E1	$00F0			MOVWF	STACK_0
$01E2	$0872			MOVF	STACK_2, 0
$01E3	$04F0			IORWF	STACK_0, 1
$01E4	$0871			MOVF	STACK_1, 0
$01E5	$04F0			IORWF	STACK_0, 1
$01E6	$09F0			COMF	STACK_0, F
$01E7	$0870			MOVF	STACK_0, 0
$01E8	$0580			ANDWF	INDF, 1
;lcd.ppas,134 :: 		
$01E9	$	lcd_L_56:
$01E9	$1784			BSF	FSR, 7
$01EA	$	lcd_L_57:
;lcd.ppas,135 :: 		
$01EA	$0825			MOVF	lcd____mdb6, 0
$01EB	$0424			IORWF	lcd____mdb7, 0
$01EC	$00F0			MOVWF	STACK_0
$01ED	$0826			MOVF	lcd____mdb5, 0
$01EE	$04F0			IORWF	STACK_0, 1
$01EF	$0827			MOVF	lcd____mdb4, 0
$01F0	$04F0			IORWF	STACK_0, 1
$01F1	$09F0			COMF	STACK_0, F
$01F2	$0870			MOVF	STACK_0, 0
$01F3	$0580			ANDWF	INDF, 1
;lcd.ppas,136 :: 		
$01F4	$1384			BCF	FSR, 7
$01F5	$	lcd_L_59:
;lcd.ppas,139 :: 		
$01F5	$0820			MOVF	lcd_ctrlport_address, 0
$01F6	$0084			MOVWF	FSR
;lcd.ppas,141 :: 		
$01F7	$0829			MOVF	lcd____mrw, 0
$01F8	$0422			IORWF	lcd____mrs, 0
$01F9	$00F0			MOVWF	STACK_0
$01FA	$0821			MOVF	lcd____menable, 0
$01FB	$04F0			IORWF	STACK_0, 1
$01FC	$09F0			COMF	STACK_0, F
$01FD	$0870			MOVF	STACK_0, 0
$01FE	$0580			ANDWF	INDF, 1
;lcd.ppas,142 :: 		
$01FF	$	lcd_L_60:
$01FF	$1784			BSF	FSR, 7
$0200	$	lcd_L_61:
;lcd.ppas,143 :: 		
$0200	$0829			MOVF	lcd____mrw, 0
$0201	$0422			IORWF	lcd____mrs, 0
$0202	$00F0			MOVWF	STACK_0
$0203	$0821			MOVF	lcd____menable, 0
$0204	$04F0			IORWF	STACK_0, 1
$0205	$09F0			COMF	STACK_0, F
$0206	$0870			MOVF	STACK_0, 0
$0207	$0580			ANDWF	INDF, 1
;lcd.ppas,144 :: 		
$0208	$1384			BCF	FSR, 7
$0209	$	lcd_L_63:
;lcd.ppas,148 :: 		
$0209	$0823			MOVF	lcd_dataport_address, 0
$020A	$0084			MOVWF	FSR
;lcd.ppas,149 :: 		
$020B	$0826			MOVF	lcd____mdb5, 0
$020C	$0400			IORWF	INDF, 0
$020D	$00F0			MOVWF	STACK_0
$020E	$0827			MOVF	lcd____mdb4, 0
$020F	$0470			IORWF	STACK_0, 0
$0210	$0080			MOVWF	INDF
;lcd.ppas,151 :: 		
$0211	$0820			MOVF	lcd_ctrlport_address, 0
$0212	$0084			MOVWF	FSR
;lcd.ppas,152 :: 		
$0213	$0821			MOVF	lcd____menable, 0
$0214	$0480			IORWF	INDF, 1
;lcd.ppas,153 :: 		
$0215	$0921			COMF	lcd____menable, W
$0216	$00F0			MOVWF	STACK_0
$0217	$0870			MOVF	STACK_0, 0
$0218	$0580			ANDWF	INDF, 1
;lcd.ppas,155 :: 		
$0219	$2651			CALL	_delay_5500us
;lcd.ppas,160 :: 		
$021A	$0821			MOVF	lcd____menable, 0
$021B	$0480			IORWF	INDF, 1
;lcd.ppas,161 :: 		
$021C	$0921			COMF	lcd____menable, W
$021D	$00F0			MOVWF	STACK_0
$021E	$0870			MOVF	STACK_0, 0
$021F	$0580			ANDWF	INDF, 1
;lcd.ppas,163 :: 		
$0220	$2651			CALL	_delay_5500us
;lcd.ppas,168 :: 		
$0221	$0821			MOVF	lcd____menable, 0
$0222	$0480			IORWF	INDF, 1
;lcd.ppas,169 :: 		
$0223	$0921			COMF	lcd____menable, W
$0224	$00F0			MOVWF	STACK_0
$0225	$0870			MOVF	STACK_0, 0
$0226	$0580			ANDWF	INDF, 1
;lcd.ppas,171 :: 		
$0227	$2651			CALL	_delay_5500us
;lcd.ppas,174 :: 		
$0228	$0823			MOVF	lcd_dataport_address, 0
$0229	$0084			MOVWF	FSR
;lcd.ppas,175 :: 		
$022A	$0826			MOVF	lcd____mdb5, 0
$022B	$0480			IORWF	INDF, 1
;lcd.ppas,176 :: 		
$022C	$0927			COMF	lcd____mdb4, W
$022D	$00F0			MOVWF	STACK_0
$022E	$0870			MOVF	STACK_0, 0
$022F	$0580			ANDWF	INDF, 1
;lcd.ppas,178 :: 		
$0230	$0820			MOVF	lcd_ctrlport_address, 0
$0231	$0084			MOVWF	FSR
;lcd.ppas,179 :: 		
$0232	$0821			MOVF	lcd____menable, 0
$0233	$0480			IORWF	INDF, 1
;lcd.ppas,180 :: 		
$0234	$0921			COMF	lcd____menable, W
$0235	$00F0			MOVWF	STACK_0
$0236	$0870			MOVF	STACK_0, 0
$0237	$0580			ANDWF	INDF, 1
;lcd.ppas,182 :: 		
$0238	$2651			CALL	_delay_5500us
;lcd.ppas,187 :: 		
$0239	$0821			MOVF	lcd____menable, 0
$023A	$0480			IORWF	INDF, 1
;lcd.ppas,188 :: 		
$023B	$0921			COMF	lcd____menable, W
$023C	$00F1			MOVWF	STACK_1
$023D	$0871			MOVF	STACK_1, 0
$023E	$0580			ANDWF	INDF, 1
;lcd.ppas,190 :: 		
$023F	$0823			MOVF	lcd_dataport_address, 0
$0240	$0084			MOVWF	FSR
;lcd.ppas,191 :: 		
$0241	$0926			COMF	lcd____mdb5, W
$0242	$00F0			MOVWF	STACK_0
$0243	$0870			MOVF	STACK_0, 0
$0244	$0580			ANDWF	INDF, 1
;lcd.ppas,192 :: 		
$0245	$0824			MOVF	lcd____mdb7, 0
$0246	$0480			IORWF	INDF, 1
;lcd.ppas,194 :: 		
$0247	$0820			MOVF	lcd_ctrlport_address, 0
$0248	$0084			MOVWF	FSR
;lcd.ppas,195 :: 		
$0249	$0821			MOVF	lcd____menable, 0
$024A	$0480			IORWF	INDF, 1
;lcd.ppas,196 :: 		
$024B	$0871			MOVF	STACK_1, 0
$024C	$0580			ANDWF	INDF, 1
;lcd.ppas,198 :: 		
$024D	$2651			CALL	_delay_5500us
;lcd.ppas,201 :: 		
$024E	$0823			MOVF	lcd_dataport_address, 0
$024F	$0084			MOVWF	FSR
;lcd.ppas,202 :: 		
$0250	$0924			COMF	lcd____mdb7, W
$0251	$00F0			MOVWF	STACK_0
$0252	$0870			MOVF	STACK_0, 0
$0253	$0580			ANDWF	INDF, 1
;lcd.ppas,203 :: 		
$0254	$0827			MOVF	lcd____mdb4, 0
$0255	$0480			IORWF	INDF, 1
;lcd.ppas,204 :: 		
$0256	$0820			MOVF	lcd_ctrlport_address, 0
$0257	$0084			MOVWF	FSR
;lcd.ppas,205 :: 		
$0258	$0821			MOVF	lcd____menable, 0
$0259	$0480			IORWF	INDF, 1
;lcd.ppas,206 :: 		
$025A	$0921			COMF	lcd____menable, W
$025B	$00F1			MOVWF	STACK_1
$025C	$0871			MOVF	STACK_1, 0
$025D	$0580			ANDWF	INDF, 1
;lcd.ppas,207 :: 		
$025E	$0823			MOVF	lcd_dataport_address, 0
$025F	$0084			MOVWF	FSR
;lcd.ppas,208 :: 		
$0260	$0927			COMF	lcd____mdb4, W
$0261	$00F0			MOVWF	STACK_0
$0262	$0870			MOVF	STACK_0, 0
$0263	$0580			ANDWF	INDF, 1
;lcd.ppas,209 :: 		
$0264	$0820			MOVF	lcd_ctrlport_address, 0
$0265	$0084			MOVWF	FSR
;lcd.ppas,210 :: 		
$0266	$0821			MOVF	lcd____menable, 0
$0267	$0480			IORWF	INDF, 1
;lcd.ppas,211 :: 		
$0268	$0871			MOVF	STACK_1, 0
$0269	$0580			ANDWF	INDF, 1
;lcd.ppas,213 :: 		
$026A	$2651			CALL	_delay_5500us
;lcd.ppas,218 :: 		
$026B	$0821			MOVF	lcd____menable, 0
$026C	$0480			IORWF	INDF, 1
;lcd.ppas,219 :: 		
$026D	$0921			COMF	lcd____menable, W
$026E	$00F0			MOVWF	STACK_0
$026F	$0870			MOVF	STACK_0, 0
$0270	$0580			ANDWF	INDF, 1
;lcd.ppas,220 :: 		
$0271	$0823			MOVF	lcd_dataport_address, 0
$0272	$0084			MOVWF	FSR
;lcd.ppas,221 :: 		
$0273	$0827			MOVF	lcd____mdb4, 0
$0274	$0480			IORWF	INDF, 1
;lcd.ppas,222 :: 		
$0275	$0820			MOVF	lcd_ctrlport_address, 0
$0276	$0084			MOVWF	FSR
;lcd.ppas,223 :: 		
$0277	$0821			MOVF	lcd____menable, 0
$0278	$0480			IORWF	INDF, 1
;lcd.ppas,224 :: 		
$0279	$0870			MOVF	STACK_0, 0
$027A	$0580			ANDWF	INDF, 1
;lcd.ppas,226 :: 		
$027B	$2651			CALL	_delay_5500us
;lcd.ppas,229 :: 		
$027C	$0823			MOVF	lcd_dataport_address, 0
$027D	$0084			MOVWF	FSR
;lcd.ppas,230 :: 		
$027E	$0927			COMF	lcd____mdb4, W
$027F	$00F0			MOVWF	STACK_0
$0280	$0870			MOVF	STACK_0, 0
$0281	$0580			ANDWF	INDF, 1
;lcd.ppas,231 :: 		
$0282	$0820			MOVF	lcd_ctrlport_address, 0
$0283	$0084			MOVWF	FSR
;lcd.ppas,232 :: 		
$0284	$0821			MOVF	lcd____menable, 0
$0285	$0480			IORWF	INDF, 1
;lcd.ppas,233 :: 		
$0286	$0921			COMF	lcd____menable, W
$0287	$00F1			MOVWF	STACK_1
$0288	$0871			MOVF	STACK_1, 0
$0289	$0580			ANDWF	INDF, 1
;lcd.ppas,234 :: 		
$028A	$0823			MOVF	lcd_dataport_address, 0
$028B	$0084			MOVWF	FSR
;lcd.ppas,235 :: 		
$028C	$0827			MOVF	lcd____mdb4, 0
$028D	$0400			IORWF	INDF, 0
$028E	$00F0			MOVWF	STACK_0
$028F	$0826			MOVF	lcd____mdb5, 0
$0290	$04F0			IORWF	STACK_0, 1
$0291	$0825			MOVF	lcd____mdb6, 0
$0292	$04F0			IORWF	STACK_0, 1
$0293	$0824			MOVF	lcd____mdb7, 0
$0294	$0470			IORWF	STACK_0, 0
$0295	$0080			MOVWF	INDF
;lcd.ppas,236 :: 		
$0296	$0820			MOVF	lcd_ctrlport_address, 0
$0297	$0084			MOVWF	FSR
;lcd.ppas,237 :: 		
$0298	$0821			MOVF	lcd____menable, 0
$0299	$0480			IORWF	INDF, 1
;lcd.ppas,238 :: 		
$029A	$0871			MOVF	STACK_1, 0
$029B	$0580			ANDWF	INDF, 1
;lcd.ppas,240 :: 		
$029C	$2651			CALL	_delay_5500us
;lcd.ppas,242 :: 		
$029D	$3001			MOVLW	1
$029E	$00A8			MOVWF	lcd_lcdcmd_status
$029F	$	lcd_L_55:
;lcd.ppas,243 :: 		
$029F	$0008			RETURN
$0681	$	_delay_22us:
;delays.pbas,17 :: 		sub procedure Delay_22us()
;delays.pbas,18 :: 		Delay_us(22)
$0681	$3007			MOVLW	7
$0682	$1303			BCF	STATUS, RP1
$0683	$1283			BCF	STATUS, RP0
$0684	$00FA			MOVWF	STACK_10
$0685	$0BFA			DECFSZ	STACK_10, F
$0686	$2E85			GOTO	$-1
$0687	$	delays_L_3:
$0687	$0008			RETURN
$0670	$	_lcd_chr_cp:
;lcd.ppas,97 :: 		
;lcd.ppas,98 :: 		
$0670	$1303			BCF	STATUS, RP1
$0671	$1283			BCF	STATUS, RP0
$0672	$01A8			CLRF	lcd_lcdcmd_status, 1
;lcd.ppas,99 :: 		
$0673	$0852			MOVF	FARG_Lcd_Chr_CP, 0
$0674	$00DB			MOVWF	FARG_Lcd_Cmd
$0675	$23CE			CALL	_lcd_cmd
;lcd.ppas,100 :: 		
$0676	$3001			MOVLW	1
$0677	$00A8			MOVWF	lcd_lcdcmd_status
$0678	$	lcd_L_48:
;lcd.ppas,101 :: 		
$0678	$0008			RETURN
$0640	$	_div_8x8_u:
$0640	$1303			BCF	STATUS, RP1
$0641	$1283			BCF	STATUS, RP0
;math.ppas,88 :: 		
;math.ppas,90 :: 		
$0642	$01F8			CLRF	STACK_8, F
;math.ppas,91 :: 		
$0643	$3008			MOVLW	8
;math.ppas,92 :: 		
$0644	$00FC			MOVWF	STACK_12
;math.ppas,93 :: 		
$0645	$0D70			RLF	STACK_0, W
;math.ppas,94 :: 		
$0646	$0DF8			RLF	STACK_8, F
;math.ppas,95 :: 		
$0647	$0874			MOVF	STACK_4, W
;math.ppas,96 :: 		
$0648	$02F8			SUBWF	STACK_8, F
;math.ppas,97 :: 		
$0649	$1803			BTFSC	STATUS, C
;math.ppas,98 :: 		
$064A	$2E4D			GOTO	$+3
;math.ppas,99 :: 		
$064B	$07F8			ADDWF	STACK_8, F
;math.ppas,100 :: 		
$064C	$1003			BCF	STATUS, C
;math.ppas,101 :: 		
$064D	$0DF0			RLF	STACK_0, F
;math.ppas,102 :: 		
$064E	$0BFC			DECFSZ	STACK_12, F
;math.ppas,103 :: 		
$064F	$2E45			GOTO	$-10
;math.ppas,104 :: 		
$0650	$	math_L_2:
;math.ppas,105 :: 		
$0650	$0008			RETURN
$05F4	$	_mul_32x32_u:
$05F4	$1303			BCF	STATUS, RP1
$05F5	$1283			BCF	STATUS, RP0
;math.ppas,1570 :: 		
;math.ppas,1578 :: 		
$05F6	$3022			MOVLW	34
;math.ppas,1579 :: 		
$05F7	$00FC			MOVWF	STACK_12
;math.ppas,1580 :: 		
$05F8	$01F8			CLRF	STACK_8
;math.ppas,1581 :: 		
$05F9	$01F9			CLRF	STACK_9
;math.ppas,1582 :: 		
$05FA	$01FA			CLRF	STACK_10
;math.ppas,1584 :: 		
$05FB	$01FB			CLRF	STACK_11
;math.ppas,1588 :: 		
$05FC	$	_NEXT:
;math.ppas,1589 :: 		
$05FC	$03FC			DECF	STACK_12, F
;math.ppas,1590 :: 		
$05FD	$1903			BTFSC	STATUS, Z
;math.ppas,1591 :: 		
$05FE	$2E2A			GOTO	_EXIT2
;math.ppas,1593 :: 		
$05FF	$1003			BCF	STATUS, C
;math.ppas,1602 :: 		
$0600	$	_LOOP:
;math.ppas,1603 :: 		
$0600	$0CFB			RRF	STACK_11, F
;math.ppas,1604 :: 		
$0601	$0CFA			RRF	STACK_10, F
;math.ppas,1605 :: 		
$0602	$0CF9			RRF	STACK_9, F
;math.ppas,1606 :: 		
$0603	$0CF8			RRF	STACK_8, F
;math.ppas,1607 :: 		
$0604	$0CF3			RRF	STACK_3, F
;math.ppas,1608 :: 		
$0605	$0CF2			RRF	STACK_2, F
;math.ppas,1609 :: 		
$0606	$0CF1			RRF	STACK_1, F
;math.ppas,1614 :: 		
$0607	$0CF0			RRF	STACK_0, F
;math.ppas,1615 :: 		
$0608	$1C03			BTFSS	STATUS, C
;math.ppas,1616 :: 		
$0609	$2DFC			GOTO	_NEXT
;math.ppas,1617 :: 		
$060A	$03FC			DECF	STACK_12, F
;math.ppas,1618 :: 		
$060B	$1903			BTFSC	STATUS, Z
;math.ppas,1625 :: 		
$060C	$2E1C			GOTO	_EXIT1
;math.ppas,1626 :: 		
$060D	$0874			MOVF	STACK_4, W
;math.ppas,1627 :: 		
$060E	$07F8			ADDWF	STACK_8, F
;math.ppas,1628 :: 		
$060F	$0875			MOVF	STACK_5, W
;math.ppas,1629 :: 		
$0610	$1803			BTFSC	STATUS, C
;math.ppas,1630 :: 		
$0611	$0F75			INCFSZ	STACK_5, W
;math.ppas,1631 :: 		
$0612	$07F9			ADDWF	STACK_9, F
;math.ppas,1632 :: 		
$0613	$0876			MOVF	STACK_6, W
;math.ppas,1633 :: 		
$0614	$1803			BTFSC	STATUS, C
;math.ppas,1634 :: 		
$0615	$0F76			INCFSZ	STACK_6, W
;math.ppas,1635 :: 		
$0616	$07FA			ADDWF	STACK_10, F
;math.ppas,1636 :: 		
$0617	$0877			MOVF	STACK_7, W
;math.ppas,1637 :: 		
$0618	$1803			BTFSC	STATUS, C
;math.ppas,1638 :: 		
$0619	$0F77			INCFSZ	STACK_7, W
;math.ppas,1640 :: 		
$061A	$07FB			ADDWF	STACK_11, F
;math.ppas,1642 :: 		
$061B	$2E00			GOTO	_LOOP
;math.ppas,1647 :: 		
$061C	$	_EXIT1:
;math.ppas,1648 :: 		
$061C	$0874			MOVF	STACK_4, W
;math.ppas,1649 :: 		
$061D	$07F8			ADDWF	STACK_8, F
;math.ppas,1650 :: 		
$061E	$0875			MOVF	STACK_5, W
;math.ppas,1651 :: 		
$061F	$1803			BTFSC	STATUS, C
;math.ppas,1652 :: 		
$0620	$0F75			INCFSZ	STACK_5, W
;math.ppas,1653 :: 		
$0621	$07F9			ADDWF	STACK_9, F
;math.ppas,1654 :: 		
$0622	$0876			MOVF	STACK_6, W
;math.ppas,1655 :: 		
$0623	$1803			BTFSC	STATUS, C
;math.ppas,1656 :: 		
$0624	$0F76			INCFSZ	STACK_6, W
;math.ppas,1657 :: 		
$0625	$07FA			ADDWF	STACK_10, F
;math.ppas,1658 :: 		
$0626	$0877			MOVF	STACK_7, W
;math.ppas,1659 :: 		
$0627	$1803			BTFSC	STATUS, C
;math.ppas,1660 :: 		
$0628	$0F77			INCFSZ	STACK_7, W
;math.ppas,1663 :: 		
$0629	$07FB			ADDWF	STACK_11, F
;math.ppas,1664 :: 		
$062A	$	_EXIT2:
;math.ppas,1665 :: 		
$062A	$	math_L_13:
;math.ppas,1666 :: 		
$062A	$0008			RETURN
$02A0	$	_sdiv3232l:
$02A0	$1303			BCF	STATUS, RP1
$02A1	$1283			BCF	STATUS, RP0
;math.ppas,539 :: 		
;math.ppas,541 :: 		
$02A2	$0874			MOVF	STACK_4, W
;math.ppas,542 :: 		
$02A3	$02F8			SUBWF	STACK_8, F
;math.ppas,543 :: 		
$02A4	$0875			MOVF	STACK_5, W
;math.ppas,544 :: 		
$02A5	$1C03			BTFSS	STATUS, C
;math.ppas,545 :: 		
$02A6	$0F75			INCFSZ	STACK_5, W
;math.ppas,546 :: 		
$02A7	$02F9			SUBWF	STACK_9, F
;math.ppas,547 :: 		
$02A8	$0876			MOVF	STACK_6, W
;math.ppas,548 :: 		
$02A9	$1C03			BTFSS	STATUS, C
;math.ppas,549 :: 		
$02AA	$0F76			INCFSZ	STACK_6, W
;math.ppas,550 :: 		
$02AB	$02FA			SUBWF	STACK_10, F
;math.ppas,551 :: 		
$02AC	$0877			MOVF	STACK_7, W
;math.ppas,552 :: 		
$02AD	$1C03			BTFSS	STATUS, C
;math.ppas,553 :: 		
$02AE	$0F77			INCFSZ	STACK_7, W
;math.ppas,554 :: 		
$02AF	$02FB			SUBWF	STACK_11, F
;math.ppas,556 :: 		
$02B0	$0DF3			RLF	STACK_3, F
;math.ppas,557 :: 		
$02B1	$3007			MOVLW	7
;math.ppas,559 :: 		
$02B2	$00FC			MOVWF	STACK_12
;math.ppas,560 :: 		
$02B3	$	LOOPS3232A:
;math.ppas,561 :: 		
$02B3	$0D73			RLF	STACK_3, W
;math.ppas,562 :: 		
$02B4	$0DF8			RLF	STACK_8, F
;math.ppas,563 :: 		
$02B5	$0DF9			RLF	STACK_9, F
;math.ppas,564 :: 		
$02B6	$0DFA			RLF	STACK_10, F
;math.ppas,565 :: 		
$02B7	$0DFB			RLF	STACK_11, F
;math.ppas,566 :: 		
$02B8	$0874			MOVF	STACK_4, W
;math.ppas,567 :: 		
$02B9	$1C73			BTFSS	STACK_3, 0
;math.ppas,569 :: 		
$02BA	$2AC9			GOTO	SADD22LA
;math.ppas,570 :: 		
$02BB	$02F8			SUBWF	STACK_8, F
;math.ppas,571 :: 		
$02BC	$0875			MOVF	STACK_5, W
;math.ppas,572 :: 		
$02BD	$1C03			BTFSS	STATUS, C
;math.ppas,573 :: 		
$02BE	$0F75			INCFSZ	STACK_5, W
;math.ppas,574 :: 		
$02BF	$02F9			SUBWF	STACK_9, F
;math.ppas,575 :: 		
$02C0	$0876			MOVF	STACK_6, W
;math.ppas,576 :: 		
$02C1	$1C03			BTFSS	STATUS, C
;math.ppas,577 :: 		
$02C2	$0F76			INCFSZ	STACK_6, W
;math.ppas,578 :: 		
$02C3	$02FA			SUBWF	STACK_10, F
;math.ppas,579 :: 		
$02C4	$0877			MOVF	STACK_7, W
;math.ppas,580 :: 		
$02C5	$1C03			BTFSS	STATUS, C
;math.ppas,581 :: 		
$02C6	$0F77			INCFSZ	STACK_7, W
;math.ppas,582 :: 		
$02C7	$02FB			SUBWF	STACK_11, F
;math.ppas,584 :: 		
$02C8	$2AD6			GOTO	SOK22LA
;math.ppas,585 :: 		
$02C9	$	SADD22LA:
;math.ppas,586 :: 		
$02C9	$07F8			ADDWF	STACK_8, F
;math.ppas,587 :: 		
$02CA	$0875			MOVF	STACK_5, W
;math.ppas,588 :: 		
$02CB	$1803			BTFSC	STATUS, C
;math.ppas,589 :: 		
$02CC	$0F75			INCFSZ	STACK_5, W
;math.ppas,590 :: 		
$02CD	$07F9			ADDWF	STACK_9, F
;math.ppas,591 :: 		
$02CE	$0876			MOVF	STACK_6, W
;math.ppas,592 :: 		
$02CF	$1803			BTFSC	STATUS, C
;math.ppas,593 :: 		
$02D0	$0F76			INCFSZ	STACK_6, W
;math.ppas,594 :: 		
$02D1	$07FA			ADDWF	STACK_10, F
;math.ppas,595 :: 		
$02D2	$0877			MOVF	STACK_7, W
;math.ppas,596 :: 		
$02D3	$1803			BTFSC	STATUS, C
;math.ppas,597 :: 		
$02D4	$0F77			INCFSZ	STACK_7, W
;math.ppas,599 :: 		
$02D5	$07FB			ADDWF	STACK_11, F
;math.ppas,600 :: 		
$02D6	$	SOK22LA:
;math.ppas,602 :: 		
$02D6	$0DF3			RLF	STACK_3, F
;math.ppas,603 :: 		
$02D7	$0BFC			DECFSZ	STACK_12, F
;math.ppas,605 :: 		
$02D8	$2AB3			GOTO	LOOPS3232A
;math.ppas,606 :: 		
$02D9	$0D72			RLF	STACK_2, W
;math.ppas,607 :: 		
$02DA	$0DF8			RLF	STACK_8, F
;math.ppas,608 :: 		
$02DB	$0DF9			RLF	STACK_9, F
;math.ppas,609 :: 		
$02DC	$0DFA			RLF	STACK_10, F
;math.ppas,610 :: 		
$02DD	$0DFB			RLF	STACK_11, F
;math.ppas,611 :: 		
$02DE	$0874			MOVF	STACK_4, W
;math.ppas,612 :: 		
$02DF	$1C73			BTFSS	STACK_3, 0
;math.ppas,614 :: 		
$02E0	$2AEF			GOTO	SADD22L8
;math.ppas,615 :: 		
$02E1	$02F8			SUBWF	STACK_8, F
;math.ppas,616 :: 		
$02E2	$0875			MOVF	STACK_5, W
;math.ppas,617 :: 		
$02E3	$1C03			BTFSS	STATUS, C
;math.ppas,618 :: 		
$02E4	$0F75			INCFSZ	STACK_5, W
;math.ppas,619 :: 		
$02E5	$02F9			SUBWF	STACK_9, F
;math.ppas,620 :: 		
$02E6	$0876			MOVF	STACK_6, W
;math.ppas,621 :: 		
$02E7	$1C03			BTFSS	STATUS, C
;math.ppas,622 :: 		
$02E8	$0F76			INCFSZ	STACK_6, W
;math.ppas,623 :: 		
$02E9	$02FA			SUBWF	STACK_10, F
;math.ppas,624 :: 		
$02EA	$0877			MOVF	STACK_7, W
;math.ppas,625 :: 		
$02EB	$1C03			BTFSS	STATUS, C
;math.ppas,626 :: 		
$02EC	$0F77			INCFSZ	STACK_7, W
;math.ppas,627 :: 		
$02ED	$02FB			SUBWF	STACK_11, F
;math.ppas,629 :: 		
$02EE	$2AFC			GOTO	SOK22L8
;math.ppas,630 :: 		
$02EF	$	SADD22L8:
;math.ppas,631 :: 		
$02EF	$07F8			ADDWF	STACK_8, F
;math.ppas,632 :: 		
$02F0	$0875			MOVF	STACK_5, W
;math.ppas,633 :: 		
$02F1	$1803			BTFSC	STATUS, C
;math.ppas,634 :: 		
$02F2	$0F75			INCFSZ	STACK_5, W
;math.ppas,635 :: 		
$02F3	$07F9			ADDWF	STACK_9, F
;math.ppas,636 :: 		
$02F4	$0876			MOVF	STACK_6, W
;math.ppas,637 :: 		
$02F5	$1803			BTFSC	STATUS, C
;math.ppas,638 :: 		
$02F6	$0F76			INCFSZ	STACK_6, W
;math.ppas,639 :: 		
$02F7	$07FA			ADDWF	STACK_10, F
;math.ppas,640 :: 		
$02F8	$0877			MOVF	STACK_7, W
;math.ppas,641 :: 		
$02F9	$1803			BTFSC	STATUS, C
;math.ppas,642 :: 		
$02FA	$0F77			INCFSZ	STACK_7, W
;math.ppas,644 :: 		
$02FB	$07FB			ADDWF	STACK_11, F
;math.ppas,645 :: 		
$02FC	$	SOK22L8:
;math.ppas,647 :: 		
$02FC	$0DF2			RLF	STACK_2, F
;math.ppas,648 :: 		
$02FD	$3007			MOVLW	7
;math.ppas,650 :: 		
$02FE	$00FC			MOVWF	STACK_12
;math.ppas,651 :: 		
$02FF	$	LOOPS3232B:
;math.ppas,652 :: 		
$02FF	$0D72			RLF	STACK_2, W
;math.ppas,653 :: 		
$0300	$0DF8			RLF	STACK_8, F
;math.ppas,654 :: 		
$0301	$0DF9			RLF	STACK_9, F
;math.ppas,655 :: 		
$0302	$0DFA			RLF	STACK_10, F
;math.ppas,656 :: 		
$0303	$0DFB			RLF	STACK_11, F
;math.ppas,657 :: 		
$0304	$0874			MOVF	STACK_4, W
;math.ppas,658 :: 		
$0305	$1C72			BTFSS	STACK_2, 0
;math.ppas,660 :: 		
$0306	$2B15			GOTO	SADD22LB
;math.ppas,661 :: 		
$0307	$02F8			SUBWF	STACK_8, F
;math.ppas,662 :: 		
$0308	$0875			MOVF	STACK_5, W
;math.ppas,663 :: 		
$0309	$1C03			BTFSS	STATUS, C
;math.ppas,664 :: 		
$030A	$0F75			INCFSZ	STACK_5, W
;math.ppas,665 :: 		
$030B	$02F9			SUBWF	STACK_9, F
;math.ppas,666 :: 		
$030C	$0876			MOVF	STACK_6, W
;math.ppas,667 :: 		
$030D	$1C03			BTFSS	STATUS, C
;math.ppas,668 :: 		
$030E	$0F76			INCFSZ	STACK_6, W
;math.ppas,669 :: 		
$030F	$02FA			SUBWF	STACK_10, F
;math.ppas,670 :: 		
$0310	$0877			MOVF	STACK_7, W
;math.ppas,671 :: 		
$0311	$1C03			BTFSS	STATUS, C
;math.ppas,672 :: 		
$0312	$0F77			INCFSZ	STACK_7, W
;math.ppas,673 :: 		
$0313	$02FB			SUBWF	STACK_11, F
;math.ppas,675 :: 		
$0314	$2B22			GOTO	SOK22LB
;math.ppas,676 :: 		
$0315	$	SADD22LB:
;math.ppas,677 :: 		
$0315	$07F8			ADDWF	STACK_8, F
;math.ppas,678 :: 		
$0316	$0875			MOVF	STACK_5, W
;math.ppas,679 :: 		
$0317	$1803			BTFSC	STATUS, C
;math.ppas,680 :: 		
$0318	$0F75			INCFSZ	STACK_5, W
;math.ppas,681 :: 		
$0319	$07F9			ADDWF	STACK_9, F
;math.ppas,682 :: 		
$031A	$0876			MOVF	STACK_6, W
;math.ppas,683 :: 		
$031B	$1803			BTFSC	STATUS, C
;math.ppas,684 :: 		
$031C	$0F76			INCFSZ	STACK_6, W
;math.ppas,685 :: 		
$031D	$07FA			ADDWF	STACK_10, F
;math.ppas,686 :: 		
$031E	$0877			MOVF	STACK_7, W
;math.ppas,687 :: 		
$031F	$1803			BTFSC	STATUS, C
;math.ppas,688 :: 		
$0320	$0F77			INCFSZ	STACK_7, W
;math.ppas,690 :: 		
$0321	$07FB			ADDWF	STACK_11, F
;math.ppas,691 :: 		
$0322	$	SOK22LB:
;math.ppas,693 :: 		
$0322	$0DF2			RLF	STACK_2, F
;math.ppas,694 :: 		
$0323	$0BFC			DECFSZ	STACK_12, F
;math.ppas,696 :: 		
$0324	$2AFF			GOTO	LOOPS3232B
;math.ppas,697 :: 		
$0325	$0D71			RLF	STACK_1, W
;math.ppas,698 :: 		
$0326	$0DF8			RLF	STACK_8, F
;math.ppas,699 :: 		
$0327	$0DF9			RLF	STACK_9, F
;math.ppas,700 :: 		
$0328	$0DFA			RLF	STACK_10, F
;math.ppas,701 :: 		
$0329	$0DFB			RLF	STACK_11, F
;math.ppas,702 :: 		
$032A	$0874			MOVF	STACK_4, W
;math.ppas,703 :: 		
$032B	$1C72			BTFSS	STACK_2, 0
;math.ppas,705 :: 		
$032C	$2B3B			GOTO	SADD22L16
;math.ppas,706 :: 		
$032D	$02F8			SUBWF	STACK_8, F
;math.ppas,707 :: 		
$032E	$0875			MOVF	STACK_5, W
;math.ppas,708 :: 		
$032F	$1C03			BTFSS	STATUS, C
;math.ppas,709 :: 		
$0330	$0F75			INCFSZ	STACK_5, W
;math.ppas,710 :: 		
$0331	$02F9			SUBWF	STACK_9, F
;math.ppas,711 :: 		
$0332	$0876			MOVF	STACK_6, W
;math.ppas,712 :: 		
$0333	$1C03			BTFSS	STATUS, C
;math.ppas,713 :: 		
$0334	$0F76			INCFSZ	STACK_6, W
;math.ppas,714 :: 		
$0335	$02FA			SUBWF	STACK_10, F
;math.ppas,715 :: 		
$0336	$0877			MOVF	STACK_7, W
;math.ppas,716 :: 		
$0337	$1C03			BTFSS	STATUS, C
;math.ppas,717 :: 		
$0338	$0F77			INCFSZ	STACK_7, W
;math.ppas,718 :: 		
$0339	$02FB			SUBWF	STACK_11, F
;math.ppas,720 :: 		
$033A	$2B48			GOTO	SOK22L16
;math.ppas,721 :: 		
$033B	$	SADD22L16:
;math.ppas,722 :: 		
$033B	$07F8			ADDWF	STACK_8, F
;math.ppas,723 :: 		
$033C	$0875			MOVF	STACK_5, W
;math.ppas,724 :: 		
$033D	$1803			BTFSC	STATUS, C
;math.ppas,725 :: 		
$033E	$0F75			INCFSZ	STACK_5, W
;math.ppas,726 :: 		
$033F	$07F9			ADDWF	STACK_9, F
;math.ppas,727 :: 		
$0340	$0876			MOVF	STACK_6, W
;math.ppas,728 :: 		
$0341	$1803			BTFSC	STATUS, C
;math.ppas,729 :: 		
$0342	$0F76			INCFSZ	STACK_6, W
;math.ppas,730 :: 		
$0343	$07FA			ADDWF	STACK_10, F
;math.ppas,731 :: 		
$0344	$0877			MOVF	STACK_7, W
;math.ppas,732 :: 		
$0345	$1803			BTFSC	STATUS, C
;math.ppas,733 :: 		
$0346	$0F77			INCFSZ	STACK_7, W
;math.ppas,735 :: 		
$0347	$07FB			ADDWF	STACK_11, F
;math.ppas,736 :: 		
$0348	$	SOK22L16:
;math.ppas,738 :: 		
$0348	$0DF1			RLF	STACK_1, F
;math.ppas,739 :: 		
$0349	$3007			MOVLW	7
;math.ppas,741 :: 		
$034A	$00FC			MOVWF	STACK_12
;math.ppas,742 :: 		
$034B	$	LOOPS3232C:
;math.ppas,743 :: 		
$034B	$0D71			RLF	STACK_1, W
;math.ppas,744 :: 		
$034C	$0DF8			RLF	STACK_8, F
;math.ppas,745 :: 		
$034D	$0DF9			RLF	STACK_9, F
;math.ppas,746 :: 		
$034E	$0DFA			RLF	STACK_10, F
;math.ppas,747 :: 		
$034F	$0DFB			RLF	STACK_11, F
;math.ppas,748 :: 		
$0350	$0874			MOVF	STACK_4, W
;math.ppas,749 :: 		
$0351	$1C71			BTFSS	STACK_1, 0
;math.ppas,751 :: 		
$0352	$2B61			GOTO	SADD22LC
;math.ppas,752 :: 		
$0353	$02F8			SUBWF	STACK_8, F
;math.ppas,753 :: 		
$0354	$0875			MOVF	STACK_5, W
;math.ppas,754 :: 		
$0355	$1C03			BTFSS	STATUS, C
;math.ppas,755 :: 		
$0356	$0F75			INCFSZ	STACK_5, W
;math.ppas,756 :: 		
$0357	$02F9			SUBWF	STACK_9, F
;math.ppas,757 :: 		
$0358	$0876			MOVF	STACK_6, W
;math.ppas,758 :: 		
$0359	$1C03			BTFSS	STATUS, C
;math.ppas,759 :: 		
$035A	$0F76			INCFSZ	STACK_6, W
;math.ppas,760 :: 		
$035B	$02FA			SUBWF	STACK_10, F
;math.ppas,761 :: 		
$035C	$0877			MOVF	STACK_7, W
;math.ppas,762 :: 		
$035D	$1C03			BTFSS	STATUS, C
;math.ppas,763 :: 		
$035E	$0F77			INCFSZ	STACK_7, W
;math.ppas,764 :: 		
$035F	$02FB			SUBWF	STACK_11, F
;math.ppas,766 :: 		
$0360	$2B6E			GOTO	SOK22LC
;math.ppas,767 :: 		
$0361	$	SADD22LC:
;math.ppas,768 :: 		
$0361	$07F8			ADDWF	STACK_8, F
;math.ppas,769 :: 		
$0362	$0875			MOVF	STACK_5, W
;math.ppas,770 :: 		
$0363	$1803			BTFSC	STATUS, C
;math.ppas,771 :: 		
$0364	$0F75			INCFSZ	STACK_5, W
;math.ppas,772 :: 		
$0365	$07F9			ADDWF	STACK_9, F
;math.ppas,773 :: 		
$0366	$0876			MOVF	STACK_6, W
;math.ppas,774 :: 		
$0367	$1803			BTFSC	STATUS, C
;math.ppas,775 :: 		
$0368	$0F76			INCFSZ	STACK_6, W
;math.ppas,776 :: 		
$0369	$07FA			ADDWF	STACK_10, F
;math.ppas,777 :: 		
$036A	$0877			MOVF	STACK_7, W
;math.ppas,778 :: 		
$036B	$1803			BTFSC	STATUS, C
;math.ppas,779 :: 		
$036C	$0F77			INCFSZ	STACK_7, W
;math.ppas,781 :: 		
$036D	$07FB			ADDWF	STACK_11, F
;math.ppas,782 :: 		
$036E	$	SOK22LC:
;math.ppas,784 :: 		
$036E	$0DF1			RLF	STACK_1, F
;math.ppas,785 :: 		
$036F	$0BFC			DECFSZ	STACK_12, F
;math.ppas,787 :: 		
$0370	$2B4B			GOTO	LOOPS3232C
;math.ppas,788 :: 		
$0371	$0D70			RLF	STACK_0, W
;math.ppas,789 :: 		
$0372	$0DF8			RLF	STACK_8, F
;math.ppas,790 :: 		
$0373	$0DF9			RLF	STACK_9, F
;math.ppas,791 :: 		
$0374	$0DFA			RLF	STACK_10, F
;math.ppas,792 :: 		
$0375	$0DFB			RLF	STACK_11, F
;math.ppas,793 :: 		
$0376	$0874			MOVF	STACK_4, W
;math.ppas,794 :: 		
$0377	$1C71			BTFSS	STACK_1, 0
;math.ppas,796 :: 		
$0378	$2B87			GOTO	SADD22L24
;math.ppas,797 :: 		
$0379	$02F8			SUBWF	STACK_8, F
;math.ppas,798 :: 		
$037A	$0875			MOVF	STACK_5, W
;math.ppas,799 :: 		
$037B	$1C03			BTFSS	STATUS, C
;math.ppas,800 :: 		
$037C	$0F75			INCFSZ	STACK_5, W
;math.ppas,801 :: 		
$037D	$02F9			SUBWF	STACK_9, F
;math.ppas,802 :: 		
$037E	$0876			MOVF	STACK_6, W
;math.ppas,803 :: 		
$037F	$1C03			BTFSS	STATUS, C
;math.ppas,804 :: 		
$0380	$0F76			INCFSZ	STACK_6, W
;math.ppas,805 :: 		
$0381	$02FA			SUBWF	STACK_10, F
;math.ppas,806 :: 		
$0382	$0877			MOVF	STACK_7, W
;math.ppas,807 :: 		
$0383	$1C03			BTFSS	STATUS, C
;math.ppas,808 :: 		
$0384	$0F77			INCFSZ	STACK_7, W
;math.ppas,809 :: 		
$0385	$02FB			SUBWF	STACK_11, F
;math.ppas,811 :: 		
$0386	$2B94			GOTO	SOK22L24
;math.ppas,812 :: 		
$0387	$	SADD22L24:
;math.ppas,813 :: 		
$0387	$07F8			ADDWF	STACK_8, F
;math.ppas,814 :: 		
$0388	$0875			MOVF	STACK_5, W
;math.ppas,815 :: 		
$0389	$1803			BTFSC	STATUS, C
;math.ppas,816 :: 		
$038A	$0F75			INCFSZ	STACK_5, W
;math.ppas,817 :: 		
$038B	$07F9			ADDWF	STACK_9, F
;math.ppas,818 :: 		
$038C	$0876			MOVF	STACK_6, W
;math.ppas,819 :: 		
$038D	$1803			BTFSC	STATUS, C
;math.ppas,820 :: 		
$038E	$0F76			INCFSZ	STACK_6, W
;math.ppas,821 :: 		
$038F	$07FA			ADDWF	STACK_10, F
;math.ppas,822 :: 		
$0390	$0877			MOVF	STACK_7, W
;math.ppas,823 :: 		
$0391	$1803			BTFSC	STATUS, C
;math.ppas,824 :: 		
$0392	$0F77			INCFSZ	STACK_7, W
;math.ppas,826 :: 		
$0393	$07FB			ADDWF	STACK_11, F
;math.ppas,827 :: 		
$0394	$	SOK22L24:
;math.ppas,829 :: 		
$0394	$0DF0			RLF	STACK_0, F
;math.ppas,830 :: 		
$0395	$3007			MOVLW	7
;math.ppas,832 :: 		
$0396	$00FC			MOVWF	STACK_12
;math.ppas,833 :: 		
$0397	$	LOOPS3232D:
;math.ppas,834 :: 		
$0397	$0D70			RLF	STACK_0, W
;math.ppas,835 :: 		
$0398	$0DF8			RLF	STACK_8, F
;math.ppas,836 :: 		
$0399	$0DF9			RLF	STACK_9, F
;math.ppas,837 :: 		
$039A	$0DFA			RLF	STACK_10, F
;math.ppas,838 :: 		
$039B	$0DFB			RLF	STACK_11, F
;math.ppas,839 :: 		
$039C	$0874			MOVF	STACK_4, W
;math.ppas,840 :: 		
$039D	$1C70			BTFSS	STACK_0, 0
;math.ppas,842 :: 		
$039E	$2BAD			GOTO	SADD22LD
;math.ppas,843 :: 		
$039F	$02F8			SUBWF	STACK_8, F
;math.ppas,844 :: 		
$03A0	$0875			MOVF	STACK_5, W
;math.ppas,845 :: 		
$03A1	$1C03			BTFSS	STATUS, C
;math.ppas,846 :: 		
$03A2	$0F75			INCFSZ	STACK_5, W
;math.ppas,847 :: 		
$03A3	$02F9			SUBWF	STACK_9, F
;math.ppas,848 :: 		
$03A4	$0876			MOVF	STACK_6, W
;math.ppas,849 :: 		
$03A5	$1C03			BTFSS	STATUS, C
;math.ppas,850 :: 		
$03A6	$0F76			INCFSZ	STACK_6, W
;math.ppas,851 :: 		
$03A7	$02FA			SUBWF	STACK_10, F
;math.ppas,852 :: 		
$03A8	$0877			MOVF	STACK_7, W
;math.ppas,853 :: 		
$03A9	$1C03			BTFSS	STATUS, C
;math.ppas,854 :: 		
$03AA	$0F77			INCFSZ	STACK_7, W
;math.ppas,855 :: 		
$03AB	$02FB			SUBWF	STACK_11, F
;math.ppas,857 :: 		
$03AC	$2BBA			GOTO	SOK22LD
;math.ppas,858 :: 		
$03AD	$	SADD22LD:
;math.ppas,859 :: 		
$03AD	$07F8			ADDWF	STACK_8, F
;math.ppas,860 :: 		
$03AE	$0875			MOVF	STACK_5, W
;math.ppas,861 :: 		
$03AF	$1803			BTFSC	STATUS, C
;math.ppas,862 :: 		
$03B0	$0F75			INCFSZ	STACK_5, W
;math.ppas,863 :: 		
$03B1	$07F9			ADDWF	STACK_9, F
;math.ppas,864 :: 		
$03B2	$0876			MOVF	STACK_6, W
;math.ppas,865 :: 		
$03B3	$1803			BTFSC	STATUS, C
;math.ppas,866 :: 		
$03B4	$0F76			INCFSZ	STACK_6, W
;math.ppas,867 :: 		
$03B5	$07FA			ADDWF	STACK_10, F
;math.ppas,868 :: 		
$03B6	$0877			MOVF	STACK_7, W
;math.ppas,870 :: 		
$03B7	$1803			BTFSC	STATUS, C
;math.ppas,871 :: 		
$03B8	$0F77			INCFSZ	STACK_7, W
;math.ppas,873 :: 		
$03B9	$07FB			ADDWF	STACK_11, F
;math.ppas,874 :: 		
$03BA	$	SOK22LD:
;math.ppas,876 :: 		
$03BA	$0DF0			RLF	STACK_0, F
;math.ppas,877 :: 		
$03BB	$0BFC			DECFSZ	STACK_12, F
;math.ppas,879 :: 		
$03BC	$2B97			GOTO	LOOPS3232D
;math.ppas,880 :: 		
$03BD	$1870			BTFSC	STACK_0, 0
;math.ppas,881 :: 		
$03BE	$2BCD			GOTO	SOK22L
;math.ppas,882 :: 		
$03BF	$0874			MOVF	STACK_4, W
;math.ppas,883 :: 		
$03C0	$07F8			ADDWF	STACK_8, F
;math.ppas,884 :: 		
$03C1	$0875			MOVF	STACK_5, W
;math.ppas,885 :: 		
$03C2	$1803			BTFSC	STATUS, C
;math.ppas,886 :: 		
$03C3	$0F75			INCFSZ	STACK_5, W
;math.ppas,887 :: 		
$03C4	$07F9			ADDWF	STACK_9, F
;math.ppas,888 :: 		
$03C5	$0876			MOVF	STACK_6, W
;math.ppas,889 :: 		
$03C6	$1803			BTFSC	STATUS, C
;math.ppas,890 :: 		
$03C7	$0F76			INCFSZ	STACK_6, W
;math.ppas,891 :: 		
$03C8	$07FA			ADDWF	STACK_10, F
;math.ppas,892 :: 		
$03C9	$0877			MOVF	STACK_7, W
;math.ppas,893 :: 		
$03CA	$1803			BTFSC	STATUS, C
;math.ppas,894 :: 		
$03CB	$0F77			INCFSZ	STACK_7, W
;math.ppas,895 :: 		
$03CC	$07FB			ADDWF	STACK_11, F
;math.ppas,896 :: 		
$03CD	$	SOK22L:
;math.ppas,897 :: 		
$03CD	$	math_L_9:
;math.ppas,898 :: 		
$03CD	$0008			RETURN
$0662	$	_comfrem:
$0662	$1303			BCF	STATUS, RP1
$0663	$1283			BCF	STATUS, RP0
;math.ppas,901 :: 		
;math.ppas,903 :: 		
$0664	$09FB			COMF	STACK_11, F
;math.ppas,904 :: 		
$0665	$09FA			COMF	STACK_10, F
;math.ppas,905 :: 		
$0666	$09F9			COMF	STACK_9, F
;math.ppas,906 :: 		
$0667	$09F8			COMF	STACK_8, F
;math.ppas,907 :: 		
$0668	$0AF8			INCF	STACK_8, F
;math.ppas,908 :: 		
$0669	$1903			BTFSC	STATUS, Z
;math.ppas,909 :: 		
$066A	$0AF9			INCF	STACK_9, F
;math.ppas,910 :: 		
$066B	$1903			BTFSC	STATUS, Z
;math.ppas,911 :: 		
$066C	$0AFA			INCF	STACK_10, F
;math.ppas,912 :: 		
$066D	$1903			BTFSC	STATUS, Z
;math.ppas,913 :: 		
$066E	$0AFB			INCF	STACK_11, F
;math.ppas,914 :: 		
$066F	$	math_L_10:
;math.ppas,915 :: 		
$066F	$0008			RETURN
$062B	$	_lcd_init:
;lcd.ppas,246 :: 		
;lcd.ppas,247 :: 		
$062B	$1303			BCF	STATUS, RP1
$062C	$1283			BCF	STATUS, RP0
$062D	$084E			MOVF	FARG_Lcd_Init, 0
$062E	$00D2			MOVWF	FARG_Lcd_Config
$062F	$3007			MOVLW	7
$0630	$00D3			MOVWF	FARG_Lcd_Config+1
$0631	$3006			MOVLW	6
$0632	$00D4			MOVWF	FARG_Lcd_Config+2
$0633	$3005			MOVLW	5
$0634	$00D5			MOVWF	FARG_Lcd_Config+3
$0635	$3004			MOVLW	4
$0636	$00D6			MOVWF	FARG_Lcd_Config+4
$0637	$084E			MOVF	FARG_Lcd_Init, 0
$0638	$00D7			MOVWF	FARG_Lcd_Config+5
$0639	$3002			MOVLW	2
$063A	$00D8			MOVWF	FARG_Lcd_Config+6
$063B	$01D9			CLRF	FARG_Lcd_Config+7, 1
$063C	$3003			MOVLW	3
$063D	$00DA			MOVWF	FARG_Lcd_Config+8
$063E	$2181			CALL	_lcd_config
$063F	$	lcd_L_64:
;lcd.ppas,248 :: 		
$063F	$0008			RETURN
$0589	$	_adc_read:
;ADClib_A_B.ppas,12 :: 		
;ADClib_A_B.ppas,13 :: 		
$0589	$3040			MOVLW	64
$058A	$1303			BCF	STATUS, RP1
$058B	$1283			BCF	STATUS, RP0
$058C	$059F			ANDWF	ADCON0, 1
;ADClib_A_B.ppas,14 :: 		
$058D	$30F0			MOVLW	240
$058E	$1683			BSF	STATUS, RP0
$058F	$049F			IORWF	ADCON1, 1
;ADClib_A_B.ppas,15 :: 		
$0590	$1283			BCF	STATUS, RP0
$0591	$179F			BSF	ADCON0, 7
;ADClib_A_B.ppas,16 :: 		
$0592	$084E			MOVF	FARG_ADC_read, 0
$0593	$00F0			MOVWF	STACK_0
$0594	$0DF0			RLF	STACK_0, 1
$0595	$1070			BCF	STACK_0, 0
$0596	$0DF0			RLF	STACK_0, 1
$0597	$1070			BCF	STACK_0, 0
$0598	$0870			MOVF	STACK_0, 0
$0599	$049F			IORWF	ADCON0, 1
;ADClib_A_B.ppas,17 :: 		
$059A	$141F			BSF	ADCON0, 0
;ADClib_A_B.ppas,18 :: 		
$059B	$2681			CALL	_delay_22us
;ADClib_A_B.ppas,19 :: 		
$059C	$149F			BSF	ADCON0, 1
;ADClib_A_B.ppas,20 :: 		
$059D	$	ADClib_A_B_L_2:
$059D	$081F			MOVF	ADCON0, 0
$059E	$00F2			MOVWF	STACK_2
$059F	$3000			MOVLW	0
$05A0	$18F2			BTFSC	STACK_2, 1
$05A1	$3001			MOVLW	1
$05A2	$00F2			MOVWF	STACK_2
$05A3	$0872			MOVF	STACK_2, 0
$05A4	$3A01			XORLW	1
$05A5	$1D03			BTFSS	STATUS, Z
$05A6	$2DA9			GOTO	ADClib_A_B_L_3
;ADClib_A_B.ppas,21 :: 		
$05A7	$0000			NOP
$05A8	$2D9D			GOTO	ADClib_A_B_L_2
$05A9	$	ADClib_A_B_L_3:
;ADClib_A_B.ppas,22 :: 		
$05A9	$081E			MOVF	ADRESH, 0
$05AA	$00F2			MOVWF	STACK_2
$05AB	$01F3			CLRF	STACK_2+1
$05AC	$0872			MOVF	STACK_2, 0
$05AD	$00F3			MOVWF	STACK_2+1
$05AE	$01F2			CLRF	STACK_2
$05AF	$0872			MOVF	STACK_2, 0
$05B0	$00CF			MOVWF	_adc_read_local_result
$05B1	$0873			MOVF	STACK_2+1, 0
$05B2	$00D0			MOVWF	_adc_read_local_result+1
;ADClib_A_B.ppas,23 :: 		
$05B3	$1683			BSF	STATUS, RP0
$05B4	$081E			MOVF	ADRESL, 0
$05B5	$0472			IORWF	STACK_2, 0
$05B6	$1283			BCF	STATUS, RP0
$05B7	$00CF			MOVWF	_adc_read_local_result
$05B8	$0873			MOVF	STACK_2+1, 0
$05B9	$00D0			MOVWF	_adc_read_local_result+1
$05BA	$3000			MOVLW	0
$05BB	$04D0			IORWF	_adc_read_local_result+1, 1
;ADClib_A_B.ppas,24 :: 		
$05BC	$101F			BCF	ADCON0, 0
$05BD	$	ADClib_A_B_L_0:
;ADClib_A_B.ppas,25 :: 		
$05BD	$084F			MOVF	_adc_read_local_result, 0
$05BE	$00F0			MOVWF	STACK_0
$05BF	$0850			MOVF	_adc_read_local_result+1, 0
$05C0	$00F1			MOVWF	STACK_0+1
$05C1	$0008			RETURN
$050F	$	_lcd_out:
;lcd.ppas,252 :: 		
;lcd.ppas,254 :: 		
$050F	$	lcd_L_68:
$050F	$1303			BCF	STATUS, RP1
$0510	$1283			BCF	STATUS, RP0
$0511	$084E			MOVF	FARG_Lcd_Out, 0
$0512	$3A01			XORLW	1
$0513	$1D03			BTFSS	STATUS, Z
$0514	$2D18			GOTO	lcd_L_69
$0515	$	lcd_L_67:
$0515	$3080			MOVLW	128
$0516	$00CE			MOVWF	FARG_Lcd_Out
$0517	$2D2F			GOTO	lcd_L_66
$0518	$	lcd_L_69:
;lcd.ppas,255 :: 		
$0518	$	lcd_L_71:
$0518	$084E			MOVF	FARG_Lcd_Out, 0
$0519	$3A02			XORLW	2
$051A	$1D03			BTFSS	STATUS, Z
$051B	$2D1F			GOTO	lcd_L_72
$051C	$	lcd_L_70:
$051C	$30C0			MOVLW	192
$051D	$00CE			MOVWF	FARG_Lcd_Out
$051E	$2D2F			GOTO	lcd_L_66
$051F	$	lcd_L_72:
;lcd.ppas,256 :: 		
$051F	$	lcd_L_74:
$051F	$084E			MOVF	FARG_Lcd_Out, 0
$0520	$3A03			XORLW	3
$0521	$1D03			BTFSS	STATUS, Z
$0522	$2D26			GOTO	lcd_L_75
$0523	$	lcd_L_73:
$0523	$3094			MOVLW	148
$0524	$00CE			MOVWF	FARG_Lcd_Out
$0525	$2D2F			GOTO	lcd_L_66
$0526	$	lcd_L_75:
;lcd.ppas,257 :: 		
$0526	$	lcd_L_77:
$0526	$084E			MOVF	FARG_Lcd_Out, 0
$0527	$3A04			XORLW	4
$0528	$1D03			BTFSS	STATUS, Z
$0529	$2D2D			GOTO	lcd_L_78
$052A	$	lcd_L_76:
$052A	$30D4			MOVLW	212
$052B	$00CE			MOVWF	FARG_Lcd_Out
;lcd.ppas,258 :: 		
$052C	$2D2F			GOTO	lcd_L_66
$052D	$	lcd_L_78:
$052D	$3080			MOVLW	128
$052E	$00CE			MOVWF	FARG_Lcd_Out
$052F	$	lcd_L_66:
;lcd.ppas,260 :: 		
$052F	$034F			DECF	FARG_Lcd_Out+1, 0
$0530	$00F0			MOVWF	STACK_0
$0531	$084E			MOVF	FARG_Lcd_Out, 0
$0532	$07F0			ADDWF	STACK_0, 1
$0533	$0870			MOVF	STACK_0, 0
$0534	$00CE			MOVWF	FARG_Lcd_Out
;lcd.ppas,261 :: 		
$0535	$0870			MOVF	STACK_0, 0
$0536	$00DB			MOVWF	FARG_Lcd_Cmd
$0537	$23CE			CALL	_lcd_cmd
;lcd.ppas,262 :: 		
$0538	$01A8			CLRF	lcd_lcdcmd_status, 1
;lcd.ppas,263 :: 		
$0539	$01D1			CLRF	_lcd_out_local_i, 1
;lcd.ppas,264 :: 		
$053A	$	lcd_L_80:
$053A	$0851			MOVF	_lcd_out_local_i, 0
$053B	$0750			ADDWF	FARG_Lcd_Out+2, 0
$053C	$0084			MOVWF	FSR
$053D	$0800			MOVF	INDF, 0
$053E	$00F2			MOVWF	STACK_2
$053F	$0872			MOVF	STACK_2, 0
$0540	$3A00			XORLW	0
$0541	$1903			BTFSC	STATUS, Z
$0542	$2D4B			GOTO	lcd_L_81
;lcd.ppas,266 :: 		
$0543	$0851			MOVF	_lcd_out_local_i, 0
$0544	$0750			ADDWF	FARG_Lcd_Out+2, 0
$0545	$0084			MOVWF	FSR
$0546	$0800			MOVF	INDF, 0
$0547	$00D2			MOVWF	FARG_Lcd_Chr_CP
$0548	$2670			CALL	_lcd_chr_cp
;lcd.ppas,267 :: 		
$0549	$0AD1			INCF	_lcd_out_local_i, 1
;lcd.ppas,268 :: 		
$054A	$2D3A			GOTO	lcd_L_80
$054B	$	lcd_L_81:
;lcd.ppas,269 :: 		
$054B	$3001			MOVLW	1
$054C	$00A8			MOVWF	lcd_lcdcmd_status
$054D	$	lcd_L_65:
;lcd.ppas,270 :: 		
$054D	$0008			RETURN
$05C2	$	_bytetostr:
;conv.ppas,8 :: 		
;conv.ppas,9 :: 		
$05C2	$3001			MOVLW	1
$05C3	$1303			BCF	STATUS, RP1
$05C4	$1283			BCF	STATUS, RP0
$05C5	$00D0			MOVWF	_bytetostr_local_len
;conv.ppas,10 :: 		
$05C6	$084E			MOVF	FARG_ByteToStr, 0
$05C7	$3C09			SUBLW	9
$05C8	$1803			BTFSC	STATUS, C
$05C9	$2DCB			GOTO	conv_L_2
$05CA	$	conv_L_1:
;conv.ppas,11 :: 		
$05CA	$0AD0			INCF	_bytetostr_local_len, 1
$05CB	$	conv_L_2:
$05CB	$	conv_L_3:
;conv.ppas,12 :: 		
$05CB	$084E			MOVF	FARG_ByteToStr, 0
$05CC	$3C63			SUBLW	99
$05CD	$1803			BTFSC	STATUS, C
$05CE	$2DD0			GOTO	conv_L_5
$05CF	$	conv_L_4:
;conv.ppas,13 :: 		
$05CF	$0AD0			INCF	_bytetostr_local_len, 1
$05D0	$	conv_L_5:
$05D0	$	conv_L_6:
;conv.ppas,14 :: 		
$05D0	$084F			MOVF	FARG_ByteToStr+1, 0
$05D1	$0084			MOVWF	FSR
$05D2	$3020			MOVLW	32
$05D3	$0080			MOVWF	INDF
$05D4	$0A84			INCF	FSR, 1
$05D5	$0080			MOVWF	INDF
$05D6	$0A84			INCF	FSR, 1
$05D7	$0080			MOVWF	INDF
$05D8	$0A84			INCF	FSR, 1
$05D9	$0180			CLRF	INDF
;conv.ppas,15 :: 		
$05DA	$0384			DECF	FSR, 1
;conv.ppas,17 :: 		
$05DB	$	conv_L_9:
$05DB	$0850			MOVF	_bytetostr_local_len, 0
$05DC	$3C00			SUBLW	0
$05DD	$1803			BTFSC	STATUS, C
$05DE	$2DF3			GOTO	conv_L_10
;conv.ppas,19 :: 		
$05DF	$300A			MOVLW	10
$05E0	$00F4			MOVWF	STACK_4
$05E1	$084E			MOVF	FARG_ByteToStr, 0
$05E2	$00F0			MOVWF	STACK_0
$05E3	$2640			CALL	_div_8x8_u
$05E4	$0878			MOVF	STACK_8, 0
$05E5	$00F0			MOVWF	STACK_0
$05E6	$3030			MOVLW	48
$05E7	$0770			ADDWF	STACK_0, 0
$05E8	$0080			MOVWF	INDF
;conv.ppas,20 :: 		
;conv.ppas,21 :: 		
$05E9	$0384			DECF	FSR, 1
;conv.ppas,22 :: 		
$05EA	$300A			MOVLW	10
$05EB	$00F4			MOVWF	STACK_4
$05EC	$084E			MOVF	FARG_ByteToStr, 0
$05ED	$00F0			MOVWF	STACK_0
$05EE	$2640			CALL	_div_8x8_u
$05EF	$0870			MOVF	STACK_0, 0
$05F0	$00CE			MOVWF	FARG_ByteToStr
;conv.ppas,23 :: 		
$05F1	$03D0			DECF	_bytetostr_local_len, 1
;conv.ppas,24 :: 		
$05F2	$2DDB			GOTO	conv_L_9
$05F3	$	conv_L_10:
$05F3	$	conv_L_0:
;conv.ppas,26 :: 		
$05F3	$0008			RETURN
$054E	$	_mul_32x32_s:
$054E	$1303			BCF	STATUS, RP1
$054F	$1283			BCF	STATUS, RP0
;math.ppas,1675 :: 		
;math.ppas,1680 :: 		
$0550	$01FD			CLRF	STACK_13
;math.ppas,1683 :: 		
$0551	$	_IF_FIRST:
;math.ppas,1684 :: 		
$0551	$1FF3			BTFSS	STACK_3, 7
;math.ppas,1686 :: 		
$0552	$2D60			GOTO	_IF_SECOND
;math.ppas,1691 :: 		
$0553	$	_INVERCE_FIRST:
;math.ppas,1692 :: 		
$0553	$09F0			COMF	STACK_0, F
;math.ppas,1693 :: 		
$0554	$09F1			COMF	STACK_1, F
;math.ppas,1694 :: 		
$0555	$09F2			COMF	STACK_2, F
;math.ppas,1701 :: 		
$0556	$09F3			COMF	STACK_3, F
;math.ppas,1702 :: 		
$0557	$0AF0			INCF	STACK_0, F
;math.ppas,1703 :: 		
$0558	$1903			BTFSC	STATUS, Z
;math.ppas,1704 :: 		
$0559	$0AF1			INCF	STACK_1, F
;math.ppas,1705 :: 		
$055A	$1903			BTFSC	STATUS, Z
;math.ppas,1706 :: 		
$055B	$0AF2			INCF	STACK_2, F
;math.ppas,1707 :: 		
$055C	$1903			BTFSC	STATUS, Z
;math.ppas,1708 :: 		
$055D	$0AF3			INCF	STACK_3, F
;math.ppas,1709 :: 		
$055E	$3081			MOVLW	129
;math.ppas,1711 :: 		
$055F	$07FD			ADDWF	STACK_13, F
;math.ppas,1714 :: 		
$0560	$	_IF_SECOND:
;math.ppas,1715 :: 		
$0560	$1FF7			BTFSS	STACK_7, 7
;math.ppas,1717 :: 		
$0561	$2D6E			GOTO	_MULT
;math.ppas,1722 :: 		
$0562	$	_INBERSE_SECOND:
;math.ppas,1723 :: 		
$0562	$09F4			COMF	STACK_4, F
;math.ppas,1724 :: 		
$0563	$09F5			COMF	STACK_5, F
;math.ppas,1725 :: 		
$0564	$09F6			COMF	STACK_6, F
;math.ppas,1732 :: 		
$0565	$09F7			COMF	STACK_7, F
;math.ppas,1733 :: 		
$0566	$0AF4			INCF	STACK_4, F
;math.ppas,1734 :: 		
$0567	$1903			BTFSC	STATUS, Z
;math.ppas,1735 :: 		
$0568	$0AF5			INCF	STACK_5, F
;math.ppas,1736 :: 		
$0569	$1903			BTFSC	STATUS, Z
;math.ppas,1737 :: 		
$056A	$0AF6			INCF	STACK_6, F
;math.ppas,1738 :: 		
$056B	$1903			BTFSC	STATUS, Z
;math.ppas,1739 :: 		
$056C	$0AF7			INCF	STACK_7, F
;math.ppas,1741 :: 		
$056D	$0AFD			INCF	STACK_13, F
;math.ppas,1742 :: 		
$056E	$	_MULT:
;math.ppas,1744 :: 		
$056E	$25F4			CALL	_mul_32x32_u
;math.ppas,1748 :: 		
$056F	$1C7D			BTFSS	STACK_13, 0
;math.ppas,1754 :: 		
$0570	$2D88			GOTO	_EXIT
;math.ppas,1755 :: 		
$0571	$09F0			COMF	STACK_0, F
;math.ppas,1756 :: 		
$0572	$09F1			COMF	STACK_1, F
;math.ppas,1757 :: 		
$0573	$09F2			COMF	STACK_2, F
;math.ppas,1763 :: 		
$0574	$09F3			COMF	STACK_3, F
;math.ppas,1764 :: 		
$0575	$09F8			COMF	STACK_8, F
;math.ppas,1765 :: 		
$0576	$09F9			COMF	STACK_9, F
;math.ppas,1766 :: 		
$0577	$09FA			COMF	STACK_10, F
;math.ppas,1776 :: 		
$0578	$09FB			COMF	STACK_11, F
;math.ppas,1777 :: 		
$0579	$0AF0			INCF	STACK_0, F
;math.ppas,1778 :: 		
$057A	$1903			BTFSC	STATUS, Z
;math.ppas,1779 :: 		
$057B	$0AF1			INCF	STACK_1, F
;math.ppas,1780 :: 		
$057C	$1903			BTFSC	STATUS, Z
;math.ppas,1781 :: 		
$057D	$0AF2			INCF	STACK_2, F
;math.ppas,1782 :: 		
$057E	$1903			BTFSC	STATUS, Z
;math.ppas,1783 :: 		
$057F	$0AF3			INCF	STACK_3, F
;math.ppas,1784 :: 		
$0580	$1903			BTFSC	STATUS, Z
;math.ppas,1785 :: 		
$0581	$0AF8			INCF	STACK_8, F
;math.ppas,1786 :: 		
$0582	$1903			BTFSC	STATUS, Z
;math.ppas,1787 :: 		
$0583	$0AF9			INCF	STACK_9, F
;math.ppas,1788 :: 		
$0584	$1903			BTFSC	STATUS, Z
;math.ppas,1789 :: 		
$0585	$0AFA			INCF	STACK_10, F
;math.ppas,1790 :: 		
$0586	$1903			BTFSC	STATUS, Z
;math.ppas,1791 :: 		
$0587	$0AFB			INCF	STACK_11, F
;math.ppas,1792 :: 		
$0588	$	_EXIT:
;math.ppas,1793 :: 		
$0588	$	math_L_14:
;math.ppas,1794 :: 		
$0588	$0008			RETURN
$0475	$	_div_32x32_s:
$0475	$1303			BCF	STATUS, RP1
$0476	$1283			BCF	STATUS, RP0
;math.ppas,925 :: 		
;math.ppas,928 :: 		
$0477	$	FXD3232S:
;math.ppas,929 :: 		
$0477	$01FC			CLRF	STACK_12
;math.ppas,930 :: 		
$0478	$1BF7			BTFSC	STACK_7, 7
;math.ppas,932 :: 		
$0479	$0AFC			INCF	STACK_12, F
;math.ppas,933 :: 		
$047A	$01FD			CLRF	STACK_13
;math.ppas,934 :: 		
$047B	$01FB			CLRF	STACK_11
;math.ppas,935 :: 		
$047C	$01FA			CLRF	STACK_10
;math.ppas,936 :: 		
$047D	$01F9			CLRF	STACK_9
;math.ppas,937 :: 		
$047E	$01F8			CLRF	STACK_8
;math.ppas,938 :: 		
$047F	$0873			MOVF	STACK_3, W
;math.ppas,939 :: 		
$0480	$0472			IORWF	STACK_2, W
;math.ppas,940 :: 		
$0481	$0471			IORWF	STACK_1, W
;math.ppas,941 :: 		
$0482	$0470			IORWF	STACK_0, W
;math.ppas,942 :: 		
$0483	$1903			BTFSC	STATUS, Z
;math.ppas,943 :: 		
$0484	$2D09			GOTO	END_ALL
;math.ppas,944 :: 		
$0485	$0873			MOVF	STACK_3, W
;math.ppas,945 :: 		
$0486	$0677			XORWF	STACK_7, W
;math.ppas,946 :: 		
$0487	$00AA			MOVWF	MATH___MATH_TEMPB
;math.ppas,947 :: 		
$0488	$1BAA			BTFSC	MATH___MATH_TEMPB, 7
;math.ppas,951 :: 		
$0489	$09FD			COMF	STACK_13, F
;math.ppas,952 :: 		
$048A	$1FF7			BTFSS	STACK_7, 7
;math.ppas,954 :: 		
$048B	$2C97			GOTO	CA3232S
;math.ppas,955 :: 		
$048C	$09F4			COMF	STACK_4, F
;math.ppas,956 :: 		
$048D	$09F5			COMF	STACK_5, F
;math.ppas,957 :: 		
$048E	$09F6			COMF	STACK_6, F
;math.ppas,958 :: 		
$048F	$09F7			COMF	STACK_7, F
;math.ppas,959 :: 		
$0490	$0AF4			INCF	STACK_4, F
;math.ppas,960 :: 		
$0491	$1903			BTFSC	STATUS, Z
;math.ppas,961 :: 		
$0492	$0AF5			INCF	STACK_5, F
;math.ppas,962 :: 		
$0493	$1903			BTFSC	STATUS, Z
;math.ppas,963 :: 		
$0494	$0AF6			INCF	STACK_6, F
;math.ppas,964 :: 		
$0495	$1903			BTFSC	STATUS, Z
;math.ppas,966 :: 		
$0496	$0AF7			INCF	STACK_7, F
;math.ppas,967 :: 		
$0497	$	CA3232S:
;math.ppas,968 :: 		
$0497	$1FF3			BTFSS	STACK_3, 7
;math.ppas,970 :: 		
$0498	$2CA4			GOTO	C3232SX
;math.ppas,971 :: 		
$0499	$09F0			COMF	STACK_0, F
;math.ppas,972 :: 		
$049A	$09F1			COMF	STACK_1, F
;math.ppas,973 :: 		
$049B	$09F2			COMF	STACK_2, F
;math.ppas,974 :: 		
$049C	$09F3			COMF	STACK_3, F
;math.ppas,975 :: 		
$049D	$0AF0			INCF	STACK_0, F
;math.ppas,976 :: 		
$049E	$1903			BTFSC	STATUS, Z
;math.ppas,977 :: 		
$049F	$0AF1			INCF	STACK_1, F
;math.ppas,978 :: 		
$04A0	$1903			BTFSC	STATUS, Z
;math.ppas,979 :: 		
$04A1	$0AF2			INCF	STACK_2, F
;math.ppas,980 :: 		
$04A2	$1903			BTFSC	STATUS, Z
;math.ppas,982 :: 		
$04A3	$0AF3			INCF	STACK_3, F
;math.ppas,983 :: 		
$04A4	$	C3232SX:
;math.ppas,984 :: 		
$04A4	$0873			MOVF	STACK_3, W
;math.ppas,985 :: 		
$04A5	$0477			IORWF	STACK_7, W
;math.ppas,986 :: 		
$04A6	$00AA			MOVWF	MATH___MATH_TEMPB
;math.ppas,987 :: 		
$04A7	$1BAA			BTFSC	MATH___MATH_TEMPB, 7
;math.ppas,988 :: 		
$04A8	$2CC5			GOTO	C3232SX1
;math.ppas,989 :: 		
$04A9	$	C3232S:
;math.ppas,992 :: 		
$04A9	$22A0			CALL	_sdiv3232l
;math.ppas,995 :: 		
$04AA	$	C3232S2:
;math.ppas,996 :: 		
$04AA	$1BFC			BTFSC	STACK_12, 7
;math.ppas,997 :: 		
$04AB	$2CE2			GOTO	C3232SX4
;math.ppas,998 :: 		
$04AC	$	C3232SOK:
;math.ppas,999 :: 		
$04AC	$1FFD			BTFSS	STACK_13, 7
;math.ppas,1000 :: 		
$04AD	$2D09			GOTO	END_ALL
;math.ppas,1001 :: 		
$04AE	$09F0			COMF	STACK_0, F
;math.ppas,1002 :: 		
$04AF	$09F1			COMF	STACK_1, F
;math.ppas,1003 :: 		
$04B0	$09F2			COMF	STACK_2, F
;math.ppas,1004 :: 		
$04B1	$09F3			COMF	STACK_3, F
;math.ppas,1005 :: 		
$04B2	$0AF0			INCF	STACK_0, F
;math.ppas,1006 :: 		
$04B3	$1903			BTFSC	STATUS, Z
;math.ppas,1007 :: 		
$04B4	$0AF1			INCF	STACK_1, F
;math.ppas,1008 :: 		
$04B5	$1903			BTFSC	STATUS, Z
;math.ppas,1009 :: 		
$04B6	$0AF2			INCF	STACK_2, F
;math.ppas,1010 :: 		
$04B7	$1903			BTFSC	STATUS, Z
;math.ppas,1012 :: 		
$04B8	$0AF3			INCF	STACK_3, F
;math.ppas,1013 :: 		
$04B9	$09F8			COMF	STACK_8, F
;math.ppas,1014 :: 		
$04BA	$09F9			COMF	STACK_9, F
;math.ppas,1015 :: 		
$04BB	$09FA			COMF	STACK_10, F
;math.ppas,1016 :: 		
$04BC	$09FB			COMF	STACK_11, F
;math.ppas,1017 :: 		
$04BD	$0AF8			INCF	STACK_8, F
;math.ppas,1018 :: 		
$04BE	$1903			BTFSC	STATUS, Z
;math.ppas,1019 :: 		
$04BF	$0AF9			INCF	STACK_9, F
;math.ppas,1020 :: 		
$04C0	$1903			BTFSC	STATUS, Z
;math.ppas,1021 :: 		
$04C1	$0AFA			INCF	STACK_10, F
;math.ppas,1022 :: 		
$04C2	$1903			BTFSC	STATUS, Z
;math.ppas,1024 :: 		
$04C3	$0AFB			INCF	STACK_11, F
;math.ppas,1025 :: 		
$04C4	$2D09			GOTO	END_ALL
;math.ppas,1026 :: 		
$04C5	$	C3232SX1:
;math.ppas,1027 :: 		
$04C5	$1FF7			BTFSS	STACK_7, 7
;math.ppas,1028 :: 		
$04C6	$2CDC			GOTO	C3232SX3
;math.ppas,1029 :: 		
$04C7	$1BF3			BTFSC	STACK_3, 7
;math.ppas,1030 :: 		
$04C8	$2CD6			GOTO	C3232SX2
;math.ppas,1031 :: 		
$04C9	$0873			MOVF	STACK_3, W
;math.ppas,1032 :: 		
$04CA	$00FB			MOVWF	STACK_11
;math.ppas,1033 :: 		
$04CB	$0872			MOVF	STACK_2, W
;math.ppas,1034 :: 		
$04CC	$00FA			MOVWF	STACK_10
;math.ppas,1035 :: 		
$04CD	$0871			MOVF	STACK_1, W
;math.ppas,1036 :: 		
$04CE	$00F9			MOVWF	STACK_9
;math.ppas,1037 :: 		
$04CF	$0870			MOVF	STACK_0, W
;math.ppas,1038 :: 		
$04D0	$00F8			MOVWF	STACK_8
;math.ppas,1039 :: 		
$04D1	$01F3			CLRF	STACK_3
;math.ppas,1040 :: 		
$04D2	$01F2			CLRF	STACK_2
;math.ppas,1041 :: 		
$04D3	$01F1			CLRF	STACK_1
;math.ppas,1042 :: 		
$04D4	$01F0			CLRF	STACK_0
;math.ppas,1043 :: 		
$04D5	$2CAC			GOTO	C3232SOK
;math.ppas,1044 :: 		
$04D6	$	C3232SX2:
;math.ppas,1045 :: 		
$04D6	$01F3			CLRF	STACK_3
;math.ppas,1046 :: 		
$04D7	$01F2			CLRF	STACK_2
;math.ppas,1047 :: 		
$04D8	$01F1			CLRF	STACK_1
;math.ppas,1048 :: 		
$04D9	$01F0			CLRF	STACK_0
;math.ppas,1049 :: 		
$04DA	$0AF0			INCF	STACK_0, F
;math.ppas,1051 :: 		
$04DB	$3400			RETLW	0X00
;math.ppas,1052 :: 		
$04DC	$	C3232SX3:
;math.ppas,1053 :: 		
$04DC	$09F3			COMF	STACK_3, F
;math.ppas,1054 :: 		
$04DD	$09F2			COMF	STACK_2, F
;math.ppas,1055 :: 		
$04DE	$09F1			COMF	STACK_1, F
;math.ppas,1057 :: 		
$04DF	$09F0			COMF	STACK_0, F
;math.ppas,1059 :: 		
$04E0	$17FC			BSF	STACK_12, 7
;math.ppas,1060 :: 		
$04E1	$2CA9			GOTO	C3232S
;math.ppas,1061 :: 		
$04E2	$	C3232SX4:
;math.ppas,1062 :: 		
$04E2	$0AF8			INCF	STACK_8, F
;math.ppas,1063 :: 		
$04E3	$1903			BTFSC	STATUS, Z
;math.ppas,1064 :: 		
$04E4	$0AF9			INCF	STACK_9, F
;math.ppas,1065 :: 		
$04E5	$1903			BTFSC	STATUS, Z
;math.ppas,1066 :: 		
$04E6	$0AFA			INCF	STACK_10, F
;math.ppas,1067 :: 		
$04E7	$1903			BTFSC	STATUS, Z
;math.ppas,1068 :: 		
$04E8	$0AFB			INCF	STACK_11, F
;math.ppas,1069 :: 		
$04E9	$0874			MOVF	STACK_4, W
;math.ppas,1070 :: 		
$04EA	$0278			SUBWF	STACK_8, W
;math.ppas,1071 :: 		
$04EB	$1D03			BTFSS	STATUS, Z
;math.ppas,1072 :: 		
$04EC	$2CAC			GOTO	C3232SOK
;math.ppas,1073 :: 		
$04ED	$0875			MOVF	STACK_5, W
;math.ppas,1074 :: 		
$04EE	$0279			SUBWF	STACK_9, W
;math.ppas,1075 :: 		
$04EF	$1D03			BTFSS	STATUS, Z
;math.ppas,1076 :: 		
$04F0	$2CAC			GOTO	C3232SOK
;math.ppas,1077 :: 		
$04F1	$0876			MOVF	STACK_6, W
;math.ppas,1078 :: 		
$04F2	$027A			SUBWF	STACK_10, W
;math.ppas,1079 :: 		
$04F3	$1D03			BTFSS	STATUS, Z
;math.ppas,1080 :: 		
$04F4	$2CAC			GOTO	C3232SOK
;math.ppas,1081 :: 		
$04F5	$0877			MOVF	STACK_7, W
;math.ppas,1082 :: 		
$04F6	$027B			SUBWF	STACK_11, W
;math.ppas,1083 :: 		
$04F7	$1D03			BTFSS	STATUS, Z
;math.ppas,1084 :: 		
$04F8	$2CAC			GOTO	C3232SOK
;math.ppas,1085 :: 		
$04F9	$01FB			CLRF	STACK_11
;math.ppas,1086 :: 		
$04FA	$01FA			CLRF	STACK_10
;math.ppas,1087 :: 		
$04FB	$01F9			CLRF	STACK_9
;math.ppas,1088 :: 		
$04FC	$01F8			CLRF	STACK_8
;math.ppas,1089 :: 		
$04FD	$0AF0			INCF	STACK_0, F
;math.ppas,1090 :: 		
$04FE	$1903			BTFSC	STATUS, Z
;math.ppas,1091 :: 		
$04FF	$0AF1			INCF	STACK_1, F
;math.ppas,1092 :: 		
$0500	$1903			BTFSC	STATUS, Z
;math.ppas,1093 :: 		
$0501	$0AF2			INCF	STACK_2, F
;math.ppas,1094 :: 		
$0502	$1903			BTFSC	STATUS, Z
;math.ppas,1095 :: 		
$0503	$0AF3			INCF	STACK_3, F
;math.ppas,1096 :: 		
$0504	$1FF3			BTFSS	STACK_3, 7
;math.ppas,1097 :: 		
$0505	$2CAC			GOTO	C3232SOK
;math.ppas,1098 :: 		
$0506	$01AA			CLRF	MATH___MATH_TEMPB
;math.ppas,1099 :: 		
$0507	$162A			BSF	MATH___MATH_TEMPB, 4
;math.ppas,1100 :: 		
$0508	$34FF			RETLW	0XFF
;math.ppas,1101 :: 		
$0509	$	END_ALL:
;math.ppas,1102 :: 		
$0509	$01AA			CLRF	MATH___MATH_TEMPB
;math.ppas,1103 :: 		
$050A	$1C7C			BTFSS	STACK_12, 0
;math.ppas,1104 :: 		
$050B	$2D0D			GOTO	AVOID_COMFREM
;math.ppas,1106 :: 		
$050C	$2662			CALL	_comfrem
;math.ppas,1108 :: 		
$050D	$	AVOID_COMFREM:
;math.ppas,1109 :: 		
$050D	$3F00			ADDLW	0X00
;math.ppas,1110 :: 		
$050E	$	math_L_11:
;math.ppas,1111 :: 		
$050E	$0008			RETURN
$0004	$	_main:
;Valvulas.pbas,17 :: 		main:
$0004	$	_main_main:
;Valvulas.pbas,18 :: 		TRISA= %00010111
$0004	$3017			MOVLW	23
$0005	$1303			BCF	STATUS, RP1
$0006	$1683			BSF	STATUS, RP0
$0007	$0085			MOVWF	TRISA
;Valvulas.pbas,19 :: 		TRISB= %00000000
$0008	$0186			CLRF	TRISB, 1
;Valvulas.pbas,20 :: 		INTCON=%00000000
$0009	$018B			CLRF	INTCON, 1
;Valvulas.pbas,21 :: 		ANSEL= %00001111
$000A	$300F			MOVLW	15
$000B	$1703			BSF	STATUS, RP1
$000C	$1283			BCF	STATUS, RP0
$000D	$009E			MOVWF	ANSEL
;Valvulas.pbas,22 :: 		ANSELH=%00000000
$000E	$019F			CLRF	ANSELH, 1
;Valvulas.pbas,24 :: 		PORTC=0
$000F	$1303			BCF	STATUS, RP1
$0010	$0187			CLRF	PORTC, 1
;Valvulas.pbas,25 :: 		LCD_INIT(PORTC)
$0011	$3007			MOVLW	PORTC
$0012	$00CE			MOVWF	FARG_Lcd_Init
$0013	$262B			CALL	_lcd_init
;Valvulas.pbas,26 :: 		LCD_CMD(Lcd_Cursor_Off)
$0014	$300C			MOVLW	12
$0015	$00DB			MOVWF	FARG_Lcd_Cmd
$0016	$23CE			CALL	_lcd_cmd
;Valvulas.pbas,27 :: 		LCD_CMD(Lcd_Clear)
$0017	$3001			MOVLW	1
$0018	$00DB			MOVWF	FARG_Lcd_Cmd
$0019	$23CE			CALL	_lcd_cmd
;Valvulas.pbas,29 :: 		portb=0
$001A	$0186			CLRF	PORTB, 1
;Valvulas.pbas,30 :: 		executa:
$001B	$	_main_executa:
;Valvulas.pbas,31 :: 		leituraTanque = Adc_Read(0)
$001B	$01CE			CLRF	FARG_ADC_read, 1
$001C	$2589			CALL	_adc_read
$001D	$0870			MOVF	STACK_0, 0
$001E	$00AB			MOVWF	_leituratanque
$001F	$0871			MOVF	STACK_0+1, 0
$0020	$00AC			MOVWF	_leituratanque+1
;Valvulas.pbas,32 :: 		valorTanque = (LongInt(leituraTanque) * 150) / 1023
$0021	$3000			MOVLW	0
$0022	$00F2			MOVWF	STACK_0+2
$0023	$00F3			MOVWF	STACK_0+3
$0024	$3096			MOVLW	150
$0025	$00F4			MOVWF	STACK_4
$0026	$01F5			CLRF	STACK_4+1
$0027	$01F6			CLRF	STACK_4+2
$0028	$01F7			CLRF	STACK_4+3
$0029	$254E			CALL	_mul_32x32_s
$002A	$30FF			MOVLW	255
$002B	$00F4			MOVWF	STACK_4
$002C	$3003			MOVLW	3
$002D	$00F5			MOVWF	STACK_4+1
$002E	$01F6			CLRF	STACK_4+2
$002F	$01F7			CLRF	STACK_4+3
$0030	$2475			CALL	_div_32x32_s
$0031	$0870			MOVF	STACK_0, 0
$0032	$00AD			MOVWF	_valortanque
;Valvulas.pbas,34 :: 		leituraPot1 = Adc_Read(1)
$0033	$3001			MOVLW	1
$0034	$00CE			MOVWF	FARG_ADC_read
$0035	$2589			CALL	_adc_read
$0036	$0870			MOVF	STACK_0, 0
$0037	$00AE			MOVWF	_leiturapot1
$0038	$0871			MOVF	STACK_0+1, 0
$0039	$00AF			MOVWF	_leiturapot1+1
;Valvulas.pbas,35 :: 		valorPot1 =(LongInt(leituraPot1) * 150) / 1023
$003A	$3000			MOVLW	0
$003B	$00F2			MOVWF	STACK_0+2
$003C	$00F3			MOVWF	STACK_0+3
$003D	$3096			MOVLW	150
$003E	$00F4			MOVWF	STACK_4
$003F	$01F5			CLRF	STACK_4+1
$0040	$01F6			CLRF	STACK_4+2
$0041	$01F7			CLRF	STACK_4+3
$0042	$254E			CALL	_mul_32x32_s
$0043	$30FF			MOVLW	255
$0044	$00F4			MOVWF	STACK_4
$0045	$3003			MOVLW	3
$0046	$00F5			MOVWF	STACK_4+1
$0047	$01F6			CLRF	STACK_4+2
$0048	$01F7			CLRF	STACK_4+3
$0049	$2475			CALL	_div_32x32_s
$004A	$0870			MOVF	STACK_0, 0
$004B	$00B0			MOVWF	_valorpot1
;Valvulas.pbas,37 :: 		leituraPot2 = Adc_Read(2)
$004C	$3002			MOVLW	2
$004D	$00CE			MOVWF	FARG_ADC_read
$004E	$2589			CALL	_adc_read
$004F	$0870			MOVF	STACK_0, 0
$0050	$00B1			MOVWF	_leiturapot2
$0051	$0871			MOVF	STACK_0+1, 0
$0052	$00B2			MOVWF	_leiturapot2+1
;Valvulas.pbas,38 :: 		valorPot2 =(LongInt(leituraPot2) * 150) / 1023
$0053	$3000			MOVLW	0
$0054	$00F2			MOVWF	STACK_0+2
$0055	$00F3			MOVWF	STACK_0+3
$0056	$3096			MOVLW	150
$0057	$00F4			MOVWF	STACK_4
$0058	$01F5			CLRF	STACK_4+1
$0059	$01F6			CLRF	STACK_4+2
$005A	$01F7			CLRF	STACK_4+3
$005B	$254E			CALL	_mul_32x32_s
$005C	$30FF			MOVLW	255
$005D	$00F4			MOVWF	STACK_4
$005E	$3003			MOVLW	3
$005F	$00F5			MOVWF	STACK_4+1
$0060	$01F6			CLRF	STACK_4+2
$0061	$01F7			CLRF	STACK_4+3
$0062	$2475			CALL	_div_32x32_s
$0063	$0870			MOVF	STACK_0, 0
$0064	$00B3			MOVWF	_valorpot2
;Valvulas.pbas,40 :: 		leituraPot3 = Adc_Read(3)
$0065	$3003			MOVLW	3
$0066	$00CE			MOVWF	FARG_ADC_read
$0067	$2589			CALL	_adc_read
$0068	$0870			MOVF	STACK_0, 0
$0069	$00B4			MOVWF	_leiturapot3
$006A	$0871			MOVF	STACK_0+1, 0
$006B	$00B5			MOVWF	_leiturapot3+1
;Valvulas.pbas,41 :: 		valorPot3 =(LongInt(leituraPot3) * 150) / 1023
$006C	$3000			MOVLW	0
$006D	$00F2			MOVWF	STACK_0+2
$006E	$00F3			MOVWF	STACK_0+3
$006F	$3096			MOVLW	150
$0070	$00F4			MOVWF	STACK_4
$0071	$01F5			CLRF	STACK_4+1
$0072	$01F6			CLRF	STACK_4+2
$0073	$01F7			CLRF	STACK_4+3
$0074	$254E			CALL	_mul_32x32_s
$0075	$30FF			MOVLW	255
$0076	$00F4			MOVWF	STACK_4
$0077	$3003			MOVLW	3
$0078	$00F5			MOVWF	STACK_4+1
$0079	$01F6			CLRF	STACK_4+2
$007A	$01F7			CLRF	STACK_4+3
$007B	$2475			CALL	_div_32x32_s
$007C	$0870			MOVF	STACK_0, 0
$007D	$00B6			MOVWF	_valorpot3
;Valvulas.pbas,44 :: 		if(valorTanque <= valorPot1) then
$007E	$082D			MOVF	_valortanque, 0
$007F	$0230			SUBWF	_valorpot1, 0
$0080	$1C03			BTFSS	STATUS, C
$0081	$2884			GOTO	Valvulas_L_2
$0082	$	Valvulas_L_1:
;Valvulas.pbas,45 :: 		portb.4 = 1    'led ligado temperatura ok
$0082	$	Valvulas_L_4:
$0082	$1606			BSF	PORTB, 4
$0083	$	Valvulas_L_5:
$0083	$2885			GOTO	Valvulas_L_3
;Valvulas.pbas,46 :: 		else
$0084	$	Valvulas_L_2:
;Valvulas.pbas,47 :: 		portb.4 = 0    'led desligado valvula fechada
$0084	$1206			BCF	PORTB, 4
$0085	$	Valvulas_L_7:
;Valvulas.pbas,48 :: 		end if
$0085	$	Valvulas_L_3:
;Valvulas.pbas,51 :: 		if(valorTanque <= valorPot2) then
$0085	$082D			MOVF	_valortanque, 0
$0086	$0233			SUBWF	_valorpot2, 0
$0087	$1C03			BTFSS	STATUS, C
$0088	$288B			GOTO	Valvulas_L_9
$0089	$	Valvulas_L_8:
;Valvulas.pbas,52 :: 		portb.5 = 1    'led ligado temperatura ok
$0089	$	Valvulas_L_11:
$0089	$1686			BSF	PORTB, 5
$008A	$	Valvulas_L_12:
$008A	$288C			GOTO	Valvulas_L_10
;Valvulas.pbas,53 :: 		else
$008B	$	Valvulas_L_9:
;Valvulas.pbas,54 :: 		portb.5 = 0    'led desligado valvula fechada
$008B	$1286			BCF	PORTB, 5
$008C	$	Valvulas_L_14:
;Valvulas.pbas,55 :: 		end if
$008C	$	Valvulas_L_10:
;Valvulas.pbas,58 :: 		if(valorTanque <= valorPot3) then
$008C	$082D			MOVF	_valortanque, 0
$008D	$0236			SUBWF	_valorpot3, 0
$008E	$1C03			BTFSS	STATUS, C
$008F	$2892			GOTO	Valvulas_L_16
$0090	$	Valvulas_L_15:
;Valvulas.pbas,59 :: 		portb.6 = 1    'led ligado temperatura ok
$0090	$	Valvulas_L_18:
$0090	$1706			BSF	PORTB, 6
$0091	$	Valvulas_L_19:
$0091	$2893			GOTO	Valvulas_L_17
;Valvulas.pbas,60 :: 		else
$0092	$	Valvulas_L_16:
;Valvulas.pbas,61 :: 		portb.6 = 0    'led desligado valvula fechada
$0092	$1306			BCF	PORTB, 6
$0093	$	Valvulas_L_21:
;Valvulas.pbas,62 :: 		end if
$0093	$	Valvulas_L_17:
;Valvulas.pbas,65 :: 		Lcd_Out(1,1,"Tanque:   C ")
$0093	$3001			MOVLW	1
$0094	$00CE			MOVWF	FARG_Lcd_Out
$0095	$3001			MOVLW	1
$0096	$00CF			MOVWF	FARG_Lcd_Out+1
$0097	$3054			MOVLW	84
$0098	$00BC			MOVWF	?main_Local_Text+0
$0099	$3061			MOVLW	97
$009A	$00BD			MOVWF	?main_Local_Text+1
$009B	$306E			MOVLW	110
$009C	$00BE			MOVWF	?main_Local_Text+2
$009D	$3071			MOVLW	113
$009E	$00BF			MOVWF	?main_Local_Text+3
$009F	$3075			MOVLW	117
$00A0	$00C0			MOVWF	?main_Local_Text+4
$00A1	$3065			MOVLW	101
$00A2	$00C1			MOVWF	?main_Local_Text+5
$00A3	$303A			MOVLW	58
$00A4	$00C2			MOVWF	?main_Local_Text+6
$00A5	$3020			MOVLW	32
$00A6	$00C3			MOVWF	?main_Local_Text+7
$00A7	$3020			MOVLW	32
$00A8	$00C4			MOVWF	?main_Local_Text+8
$00A9	$3020			MOVLW	32
$00AA	$00C5			MOVWF	?main_Local_Text+9
$00AB	$3043			MOVLW	67
$00AC	$00C6			MOVWF	?main_Local_Text+10
$00AD	$3020			MOVLW	32
$00AE	$00C7			MOVWF	?main_Local_Text+11
$00AF	$01C8			CLRF	?main_Local_Text+12
$00B0	$303C			MOVLW	?main_Local_Text
$00B1	$00D0			MOVWF	FARG_Lcd_Out+2
$00B2	$250F			CALL	_lcd_out
;Valvulas.pbas,66 :: 		ByteToStr(valorTanque,texto)
$00B3	$082D			MOVF	_valortanque, 0
$00B4	$00CE			MOVWF	FARG_ByteToStr
$00B5	$3037			MOVLW	_texto
$00B6	$00CF			MOVWF	FARG_ByteToStr+1
$00B7	$25C2			CALL	_bytetostr
;Valvulas.pbas,67 :: 		Lcd_Out(1,8,texto)
$00B8	$3001			MOVLW	1
$00B9	$00CE			MOVWF	FARG_Lcd_Out
$00BA	$3008			MOVLW	8
$00BB	$00CF			MOVWF	FARG_Lcd_Out+1
$00BC	$3037			MOVLW	_texto
$00BD	$00D0			MOVWF	FARG_Lcd_Out+2
$00BE	$250F			CALL	_lcd_out
;Valvulas.pbas,69 :: 		Lcd_Out(2,1,"1a Valvula:    C ")
$00BF	$3002			MOVLW	2
$00C0	$00CE			MOVWF	FARG_Lcd_Out
$00C1	$3001			MOVLW	1
$00C2	$00CF			MOVWF	FARG_Lcd_Out+1
$00C3	$3031			MOVLW	49
$00C4	$00BC			MOVWF	?main_Local_Text+0
$00C5	$3061			MOVLW	97
$00C6	$00BD			MOVWF	?main_Local_Text+1
$00C7	$3020			MOVLW	32
$00C8	$00BE			MOVWF	?main_Local_Text+2
$00C9	$3056			MOVLW	86
$00CA	$00BF			MOVWF	?main_Local_Text+3
$00CB	$3061			MOVLW	97
$00CC	$00C0			MOVWF	?main_Local_Text+4
$00CD	$306C			MOVLW	108
$00CE	$00C1			MOVWF	?main_Local_Text+5
$00CF	$3076			MOVLW	118
$00D0	$00C2			MOVWF	?main_Local_Text+6
$00D1	$3075			MOVLW	117
$00D2	$00C3			MOVWF	?main_Local_Text+7
$00D3	$306C			MOVLW	108
$00D4	$00C4			MOVWF	?main_Local_Text+8
$00D5	$3061			MOVLW	97
$00D6	$00C5			MOVWF	?main_Local_Text+9
$00D7	$303A			MOVLW	58
$00D8	$00C6			MOVWF	?main_Local_Text+10
$00D9	$3020			MOVLW	32
$00DA	$00C7			MOVWF	?main_Local_Text+11
$00DB	$3020			MOVLW	32
$00DC	$00C8			MOVWF	?main_Local_Text+12
$00DD	$3020			MOVLW	32
$00DE	$00C9			MOVWF	?main_Local_Text+13
$00DF	$3020			MOVLW	32
$00E0	$00CA			MOVWF	?main_Local_Text+14
$00E1	$3043			MOVLW	67
$00E2	$00CB			MOVWF	?main_Local_Text+15
$00E3	$3020			MOVLW	32
$00E4	$00CC			MOVWF	?main_Local_Text+16
$00E5	$01CD			CLRF	?main_Local_Text+17
$00E6	$303C			MOVLW	?main_Local_Text
$00E7	$00D0			MOVWF	FARG_Lcd_Out+2
$00E8	$250F			CALL	_lcd_out
;Valvulas.pbas,70 :: 		ByteToStr(valorPot1, texto)
$00E9	$0830			MOVF	_valorpot1, 0
$00EA	$00CE			MOVWF	FARG_ByteToStr
$00EB	$3037			MOVLW	_texto
$00EC	$00CF			MOVWF	FARG_ByteToStr+1
$00ED	$25C2			CALL	_bytetostr
;Valvulas.pbas,71 :: 		Lcd_Out(2,12, texto)
$00EE	$3002			MOVLW	2
$00EF	$00CE			MOVWF	FARG_Lcd_Out
$00F0	$300C			MOVLW	12
$00F1	$00CF			MOVWF	FARG_Lcd_Out+1
$00F2	$3037			MOVLW	_texto
$00F3	$00D0			MOVWF	FARG_Lcd_Out+2
$00F4	$250F			CALL	_lcd_out
;Valvulas.pbas,73 :: 		Lcd_Out(3,1,"2a Valvula:    C ")
$00F5	$3003			MOVLW	3
$00F6	$00CE			MOVWF	FARG_Lcd_Out
$00F7	$3001			MOVLW	1
$00F8	$00CF			MOVWF	FARG_Lcd_Out+1
$00F9	$3032			MOVLW	50
$00FA	$00BC			MOVWF	?main_Local_Text+0
$00FB	$3061			MOVLW	97
$00FC	$00BD			MOVWF	?main_Local_Text+1
$00FD	$3020			MOVLW	32
$00FE	$00BE			MOVWF	?main_Local_Text+2
$00FF	$3056			MOVLW	86
$0100	$00BF			MOVWF	?main_Local_Text+3
$0101	$3061			MOVLW	97
$0102	$00C0			MOVWF	?main_Local_Text+4
$0103	$306C			MOVLW	108
$0104	$00C1			MOVWF	?main_Local_Text+5
$0105	$3076			MOVLW	118
$0106	$00C2			MOVWF	?main_Local_Text+6
$0107	$3075			MOVLW	117
$0108	$00C3			MOVWF	?main_Local_Text+7
$0109	$306C			MOVLW	108
$010A	$00C4			MOVWF	?main_Local_Text+8
$010B	$3061			MOVLW	97
$010C	$00C5			MOVWF	?main_Local_Text+9
$010D	$303A			MOVLW	58
$010E	$00C6			MOVWF	?main_Local_Text+10
$010F	$3020			MOVLW	32
$0110	$00C7			MOVWF	?main_Local_Text+11
$0111	$3020			MOVLW	32
$0112	$00C8			MOVWF	?main_Local_Text+12
$0113	$3020			MOVLW	32
$0114	$00C9			MOVWF	?main_Local_Text+13
$0115	$3020			MOVLW	32
$0116	$00CA			MOVWF	?main_Local_Text+14
$0117	$3043			MOVLW	67
$0118	$00CB			MOVWF	?main_Local_Text+15
$0119	$3020			MOVLW	32
$011A	$00CC			MOVWF	?main_Local_Text+16
$011B	$01CD			CLRF	?main_Local_Text+17
$011C	$303C			MOVLW	?main_Local_Text
$011D	$00D0			MOVWF	FARG_Lcd_Out+2
$011E	$250F			CALL	_lcd_out
;Valvulas.pbas,74 :: 		ByteToStr(valorPot2, texto)
$011F	$0833			MOVF	_valorpot2, 0
$0120	$00CE			MOVWF	FARG_ByteToStr
$0121	$3037			MOVLW	_texto
$0122	$00CF			MOVWF	FARG_ByteToStr+1
$0123	$25C2			CALL	_bytetostr
;Valvulas.pbas,75 :: 		Lcd_Out(3,12, texto)
$0124	$3003			MOVLW	3
$0125	$00CE			MOVWF	FARG_Lcd_Out
$0126	$300C			MOVLW	12
$0127	$00CF			MOVWF	FARG_Lcd_Out+1
$0128	$3037			MOVLW	_texto
$0129	$00D0			MOVWF	FARG_Lcd_Out+2
$012A	$250F			CALL	_lcd_out
;Valvulas.pbas,77 :: 		Lcd_Out(4,1,"3a Valvula:    C ")
$012B	$3004			MOVLW	4
$012C	$00CE			MOVWF	FARG_Lcd_Out
$012D	$3001			MOVLW	1
$012E	$00CF			MOVWF	FARG_Lcd_Out+1
$012F	$3033			MOVLW	51
$0130	$00BC			MOVWF	?main_Local_Text+0
$0131	$3061			MOVLW	97
$0132	$00BD			MOVWF	?main_Local_Text+1
$0133	$3020			MOVLW	32
$0134	$00BE			MOVWF	?main_Local_Text+2
$0135	$3056			MOVLW	86
$0136	$00BF			MOVWF	?main_Local_Text+3
$0137	$3061			MOVLW	97
$0138	$00C0			MOVWF	?main_Local_Text+4
$0139	$306C			MOVLW	108
$013A	$00C1			MOVWF	?main_Local_Text+5
$013B	$3076			MOVLW	118
$013C	$00C2			MOVWF	?main_Local_Text+6
$013D	$3075			MOVLW	117
$013E	$00C3			MOVWF	?main_Local_Text+7
$013F	$306C			MOVLW	108
$0140	$00C4			MOVWF	?main_Local_Text+8
$0141	$3061			MOVLW	97
$0142	$00C5			MOVWF	?main_Local_Text+9
$0143	$303A			MOVLW	58
$0144	$00C6			MOVWF	?main_Local_Text+10
$0145	$3020			MOVLW	32
$0146	$00C7			MOVWF	?main_Local_Text+11
$0147	$3020			MOVLW	32
$0148	$00C8			MOVWF	?main_Local_Text+12
$0149	$3020			MOVLW	32
$014A	$00C9			MOVWF	?main_Local_Text+13
$014B	$3020			MOVLW	32
$014C	$00CA			MOVWF	?main_Local_Text+14
$014D	$3043			MOVLW	67
$014E	$00CB			MOVWF	?main_Local_Text+15
$014F	$3020			MOVLW	32
$0150	$00CC			MOVWF	?main_Local_Text+16
$0151	$01CD			CLRF	?main_Local_Text+17
$0152	$303C			MOVLW	?main_Local_Text
$0153	$00D0			MOVWF	FARG_Lcd_Out+2
$0154	$250F			CALL	_lcd_out
;Valvulas.pbas,79 :: 		ByteToStr(valorPot3, texto)
$0155	$0836			MOVF	_valorpot3, 0
$0156	$00CE			MOVWF	FARG_ByteToStr
$0157	$3037			MOVLW	_texto
$0158	$00CF			MOVWF	FARG_ByteToStr+1
$0159	$25C2			CALL	_bytetostr
;Valvulas.pbas,80 :: 		Lcd_Out(4,12, texto)
$015A	$3004			MOVLW	4
$015B	$00CE			MOVWF	FARG_Lcd_Out
$015C	$300C			MOVLW	12
$015D	$00CF			MOVWF	FARG_Lcd_Out+1
$015E	$3037			MOVLW	_texto
$015F	$00D0			MOVWF	FARG_Lcd_Out+2
$0160	$250F			CALL	_lcd_out
;Valvulas.pbas,82 :: 		delay_ms(1000)
$0161	$3006			MOVLW	6
$0162	$00FC			MOVWF	STACK_12
$0163	$30FF			MOVLW	255
$0164	$00FB			MOVWF	STACK_11
$0165	$30FF			MOVLW	255
$0166	$00FA			MOVWF	STACK_10
$0167	$0BFC			DECFSZ	STACK_12, F
$0168	$296A			GOTO	$+2
$0169	$2971			GOTO	$+8
$016A	$0BFB			DECFSZ	STACK_11, F
$016B	$296D			GOTO	$+2
$016C	$2970			GOTO	$+4
$016D	$0BFA			DECFSZ	STACK_10, F
$016E	$296D			GOTO	$-1
$016F	$296A			GOTO	$-5
$0170	$2967			GOTO	$-9
$0171	$301A			MOVLW	26
$0172	$00FB			MOVWF	STACK_11
$0173	$30FF			MOVLW	255
$0174	$00FA			MOVWF	STACK_10
$0175	$0BFB			DECFSZ	STACK_11, F
$0176	$2978			GOTO	$+2
$0177	$297B			GOTO	$+4
$0178	$0BFA			DECFSZ	STACK_10, F
$0179	$2978			GOTO	$-1
$017A	$2975			GOTO	$-5
$017B	$3042			MOVLW	66
$017C	$00FA			MOVWF	STACK_10
$017D	$0BFA			DECFSZ	STACK_10, F
$017E	$297D			GOTO	$-1
;Valvulas.pbas,83 :: 		goto executa
$017F	$281B			GOTO	_main_executa
$0180	$2980			GOTO	$
